v2.0

diff --git a/Cocoa/clean_all b/Cocoa/clean_all
--- a/Cocoa/clean_all
+++ b/Cocoa/clean_all
@@ -1,77 +1,35 @@
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ------------------------------ Basic Settings ------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
 
-if [ -n "${SET_INSTALLATION_OPTIONS}" ]; then
-  source $SET_INSTALLATION_OPTIONS
-else
-  source set_installation_options
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
-
-source $ROOTDIR/installation_scripts/clean_camb
-source $ROOTDIR/installation_scripts/clean_class
-source $ROOTDIR/installation_scripts/clean_cosmolike
-source $ROOTDIR/installation_scripts/clean_planck
-source $ROOTDIR/installation_scripts/clean_polychord
-source $ROOTDIR/installation_scripts/clean_required
-
-deactivate
-
-if [ -n "${OLD_OMP_NUM_THREADS}" ]; then
-  export OMP_NUM_THREADS=$OLD_OMP_NUM_THREADS
-  unset OLD_OMP_NUM_THREADS
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+if [ -z "${IGNORE_CAMB_COMPILATION}" ]; then
+    source $ROOTDIR/installation_scripts/clean_camb
+    source $ROOTDIR/installation_scripts/clean_cambede
 fi
-
-if [ -n "${OLD_LD_LIBRARY_PATH}" ]; then
-  export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
-  unset OLD_LD_LIBRARY_PATH
+if [ -z "${IGNORE_CLASS_COMPILATION}" ]; then
+    source $ROOTDIR/installation_scripts/clean_class
 fi
-
-if [ -n "${OLD_PYTHONPATH}" ]; then
-  export PYTHONPATH=$OLD_PYTHONPATH
-  unset OLD_PYTHONPATH
+if [ -z "${IGNORE_PLANCK_COMPILATION}" ]; then
+    source $ROOTDIR/installation_scripts/clean_planck
 fi
-
-if [ -n "${OLD_PATH}" ]; then
-  export PATH=$OLD_PATH
-  unset OLD_PATH
+if [ -z "${IGNORE_POLYCHORD_COMPILATION}" ]; then
+    source $ROOTDIR/installation_scripts/clean_polychord
 fi
-
-if [ -n "${OLD_C_INCLUDE_PATH}" ]; then
-  export C_INCLUDE_PATH=$OLD_C_INCLUDE_PATH
-  unset OLD_C_INCLUDE_PATH
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
-
-if [ -n "${OLD_CPLUS_INCLUDE_PATH}" ]; then
-  export CPLUS_INCLUDE_PATH=$OLD_CPLUS_INCLUDE_PATH
-  unset OLD_CPLUS_INCLUDE_PATH
-fi
-
-if [ -n "${OLD_LDFLAGS}" ]; then
-  export LDFLAGS=$OLD_LDFLAGS
-  unset OLD_LDFLAGS
-fi
-
-if [ -n "${OLD_CPATH}" ]; then
-  export CPATH=$OLD_CPATH
-  unset OLD_CPATH
-fi
-
-if [ -n "${OLD_NUMPY_HEADERS}" ]; then
-  export NUMPY_HEADERS=$OLD_NUMPY_HEADERS
-  unset OLD_NUMPY_HEADERS
-fi
-
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
 
 cd $ROOTDIR/external_modules
-
 find . -maxdepth 12 -name '*.pyc' -delete
 find . -maxdepth 12 -name '*.o' -delete
 find . -maxdepth 12 -name '*.pyo' -delete
@@ -79,40 +37,18 @@ find . -maxdepth 12 -name '*.mod' -delete
 find . -maxdepth 12 -name '*.so' -delete
 find . -maxdepth 12 -name '*.a' -delete
 
-cd ./data
-
+cd $ROOTDIR/external_modules/data
 sh clean_all.sh
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
+fi
 
+source $ROOTDIR/../cocoa_installation_libraries/clean_all
 cd $ROOTDIR
-
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-
-if [ -n "${OLD_OMP_NUM_THREADS}" ]; then
-    export OMP_NUM_THREADS=$OLD_OMP_NUM_THREADS
-    unset OLD_OMP_NUM_THREADS
-fi
-
-if [ -n "${OLD_LD_LIBRARY_PATH}" ]; then
-    export LD_LIBRARY_PATH=$OLD_LD_LIBRARY_PATH
-    unset OLD_LD_LIBRARY_PATH
-fi
-
-if [ -n "${OLD_PYTHONPATH}" ]; then
-    export PYTHONPATH=$OLD_PYTHONPATH
-    unset OLD_PYTHONPATH
-fi
-
-if [ -n "${OLD_PATH}" ]; then
-    export PATH=$OLD_PATH
-    unset OLD_PATH
-fi
-
-source ./installation_scripts/impl_unset_keys.sh
-unset ROOTDIR
-unset SETUP_COBAYA
-unset SETUP_PREREQUISITE_DONE
-unset SET_INSTALLATION_OPTIONS
+source stop_cocoa
+rm -rf ./.local/
diff --git a/Cocoa/installation_scripts/clean_camb b/Cocoa/installation_scripts/clean_camb
--- a/Cocoa/installation_scripts/clean_camb
+++ b/Cocoa/installation_scripts/clean_camb
@@ -1,10 +1,10 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
-    return
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 
 # ----------------------------------------------------------------------------
@@ -12,6 +12,7 @@ fi
 # ------------------------------- REMOVE CAMB --------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING CAMB'
 
 cd $ROOTDIR/external_modules/code/CAMB/
 
@@ -23,6 +24,19 @@ rm -f ./camb/camblib.so
 
 rm -rf ./forutils/Releaselib/
 
-$PYTHON3 setup.py clean
+if [ -z "${DEBUG_CAMB_OUTPUT}" ]; then
+  export OUTPUT_CAMB_1="/dev/null"
+  export OUTPUT_CAMB_2="/dev/null"
+else
+  export OUTPUT_CAMB_1="/dev/tty"
+  export OUTPUT_CAMB_2="/dev/tty"
+fi
+
+$PYTHON3 setup.py clean > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
+if [ $? -ne 0 ]; then
+  echo "CAMB COULD NOT RUN PYTHON3 SETUP.PY CLEAN"
+else
+  echo "CAMB PYTHON3 SETUP.PY CLEAN DONE"
+fi
 
 cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/clean_planck b/Cocoa/installation_scripts/clean_planck
--- a/Cocoa/installation_scripts/clean_planck
+++ b/Cocoa/installation_scripts/clean_planck
@@ -1,10 +1,10 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
-    return
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 
 # ----------------------------------------------------------------------------
@@ -12,6 +12,7 @@ fi
 # ------------------------- REMOVE PLANCK LIKELIHOOD -------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING PLANCK LIKELIHOOD'
 
 rm -f $ROOTDIR/.local/bin/clik*
 
@@ -25,35 +26,28 @@ rm -rf $ROOTDIR/.local/share/clik
 
 rm -f $ROOTDIR/.local/include/clik*
 
-cd $ROOTDIR/external_modules/code/planck/code/plc_3.0/plc-3.01/
+if [ -z "${USE_SPT_CLIK_PLANCK}" ]; then
+  cd $ROOTDIR/external_modules/code/planck/code/plc_3.0/plc-3.1/
+else
+  cd $ROOTDIR/external_modules/code/planck/code/spt_clik/
+fi
 
 rm -f .lock-waf_*
 
-$PYTHON3 waf uninstall
-
-$PYTHON3 waf clean
-
-$PYTHON3 waf distclean
-
-if [ -n "${OLD_CLIK_PATH}" ]; then
-    export CLIK_PATH=$OLD_CLIK_PATH
-    unset OLD_CLIK_PATH
+if [ -z "${DEBUG_PLANCK_OUTPUT}" ]; then
+  export OUTPUT_PLANCK_1="/dev/null"
+  export OUTPUT_PLANCK_2="/dev/null"
 else
-    unset CLIK_PATH
+  export OUTPUT_PLANCK_1="/dev/tty"
+  export OUTPUT_PLANCK_2="/dev/tty"
 fi
 
-if [ -n "${OLD_CLIK_DATA}" ]; then
-    export CLIK_DATA=$OLD_CLIK_DATA
-    unset OLD_CLIK_DATA
+$PYTHON3 waf distclean > ${OUTPUT_PLANCK_1} 2> ${OUTPUT_PLANCK_2}
+if [ $? -ne 0 ]; then
+  echo "PLANCK COULD NOT RUN WAF DISTCLEAN"
 else
-    unset CLIK_DATA
+  echo "PLANCK WAF DISTCLEAN DONE"
 fi
 
-if [ -n "${OLD_CLIK_PLUGIN}" ]; then
-    export CLIK_PLUGIN=$OLD_CLIK_PLUGIN
-    unset OLD_CLIK_PLUGIN
-else
-    unset CLIK_PLUGIN
-fi
-
+echo 'CLEANING PLANCK LIKELIHOOD DONE'
 cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/clean_polychord b/Cocoa/installation_scripts/clean_polychord
--- a/Cocoa/installation_scripts/clean_polychord
+++ b/Cocoa/installation_scripts/clean_polychord
@@ -1,10 +1,10 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return 1
+  echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+  return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not define'
-    return 1
+  echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+  return 1
 fi
 
 # ----------------------------------------------------------------------------
@@ -12,11 +12,26 @@ fi
 # ----------------------------- REMOVE POLYCHORD ------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+echo 'CLEANING POLYCHORD'
+
+if [ -z "${DEBUG_POLY_OUTPUT}" ]; then
+  export OUTPUT_POLY_1="/dev/null"
+  export OUTPUT_POLY_2="/dev/null"
+else
+  export OUTPUT_POLY_1="/dev/tty"
+  export OUTPUT_POLY_2="/dev/tty"
+fi
 
 rm -rf $ROOTDIR/.local/lib/python3.6/site-packages/pypolychord-1.16-py3.6-linux-x86_64.egg
 
 cd $ROOTDIR/external_modules/code/PolyChordLite/
 
-make clean
+make clean > ${OUTPUT_POLY_1} 2> ${OUTPUT_POLY_2}
+if [ $? -ne 0 ]; then
+  echo "POLYCHORD COULD NOT RUN MAKE CLEAN"
+else
+  echo "POLYCHORD MAKE CLEAN RUN DONE"
+fi
 
+echo 'CLEANING POLYCHORD DONE'
 cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/clean_required b/Cocoa/installation_scripts/clean_required
--- a/Cocoa/installation_scripts/clean_required
+++ b/Cocoa/installation_scripts/clean_required
@@ -1,11 +1,7 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not define'
-    return
+  echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+  return 1
 fi
-
-echo 'Warning: all local required packages will be deleted'
-
-rm -rf $ROOTDIR/.local/
 
 cd $ROOTDIR/../cocoa_installation_libraries
 
diff --git a/Cocoa/installation_scripts/compile_camb b/Cocoa/installation_scripts/compile_camb
--- a/Cocoa/installation_scripts/compile_camb
+++ b/Cocoa/installation_scripts/compile_camb
@@ -1,21 +1,25 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not defined'
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
 # ----------------------------------------------------------------------------
@@ -37,12 +41,31 @@ if [ -z "${IGNORE_CAMB_COMPILATION}" ]; then
 
     rm -rf ./forutils/Releaselib/
 
-    $PYTHON3 setup.py clean
+    if [ -z "${DEBUG_CAMB_OUTPUT}" ]; then
+      export OUTPUT_CAMB_1="/dev/null"
+      export OUTPUT_CAMB_2="/dev/null"
+    else
+      export OUTPUT_CAMB_1="/dev/tty"
+      export OUTPUT_CAMB_2="/dev/tty"
+    fi
 
-    COMPILER=$FORTRAN_COMPILER F90C=$FORTRAN_COMPILER $PYTHON3 setup.py build
-    if [ $? -ne 0 ] 
-    then
-      echo "PROBLEM BUILDING CAMB"
+    $PYTHON3 setup.py clean > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
+    if [ $? -ne 0 ]; then
+      echo "CAMB COULD NOT RUN PYTHON3 SETUP.PY CLEAN"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CAMB PYTHON3 SETUP.PY CLEAN DONE"
+    fi
+
+    COMPILER=$FORTRAN_COMPILER F90C=$FORTRAN_COMPILER $PYTHON3 setup.py build \
+      > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
+    if [ $? -ne 0 ]; then
+      echo "CAMB COULD NOT RUN PYTHON3 SETUP.PY BUILD"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CAMB PYTHON3 SETUP.PY BUILD DONE"
     fi
 
     cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/compile_class b/Cocoa/installation_scripts/compile_class
--- a/Cocoa/installation_scripts/compile_class
+++ b/Cocoa/installation_scripts/compile_class
@@ -1,22 +1,26 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not defined'
-    return
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
+    return 1
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -29,26 +33,54 @@ if [ -z "${IGNORE_CLASS_COMPILATION}" ]; then
 
     cd $ROOTDIR/external_modules/code/class_public/
 
-    make clean
+    if [ -z "${DEBUG_CLASS_OUTPUT}" ]; then
+      export OUTPUT_CLASS_1="/dev/null"
+      export OUTPUT_CLASS_2="/dev/null"
+    else
+      export OUTPUT_CLASS_1="/dev/tty"
+      export OUTPUT_CLASS_2="/dev/tty"
+    fi
+
+    make clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+    if [ $? -ne 0 ]; then
+      echo "CLASS COULD NOT RUN MAKE CLEAN"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CLASS MAKE CLEAN RUN DONE"
+    fi
 
     rm -f class
 
-    CC=$C_COMPILER PYTHON=$PYTHON3 make -j $MAKE_NUM_THREADS
-    if [ $? -ne 0 ] 
-    then
-      echo "PROBLEM MAKE CLASS"
+    CC=$C_COMPILER PYTHON=$PYTHON3 make -j $MAKE_NUM_THREADS > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+    if [ $? -ne 0 ]; then
+      echo "CLASS COULD NOT RUN MAKE"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CLASS MAKE RUN DONE"
     fi
 
     cd ./python
 
-    $PYTHON3 setup.py clean
+    $PYTHON3 setup.py clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+    if [ $? -ne 0 ]; then
+      echo "CLASS COULD NOT PYTHON3 SETUP.PY CLEAN"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CLASS PYTHON3 SETUP.PY CLEAN DONE"
+    fi
 
     rm -rf ./build/
 
-    CC=$C_COMPILER $PYTHON3 setup.py build
-    if [ $? -ne 0 ] 
-    then
-      echo "PROBLEM BUILDING CLASS"
+    CC=$C_COMPILER $PYTHON3 setup.py build > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+    if [ $? -ne 0 ]; then
+      echo "CLASS COULD NOT PYTHON3 SETUP.PY BUILD"
+      cd $ROOTDIR
+      return 1
+    else
+      echo "CLASS PYTHON3 SETUP.PY BUILD DONE"
     fi
 
     cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/compile_planck b/Cocoa/installation_scripts/compile_planck
--- a/Cocoa/installation_scripts/compile_planck
+++ b/Cocoa/installation_scripts/compile_planck
@@ -1,21 +1,21 @@
 if [ -z "${ROOTDIR}" ]; then
-  echo 'ERROR ROOTDIR not defined'
-  return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-  echo 'ERROR CXX_COMPILER not defined'
-  return 1
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-  echo 'ERROR C_COMPILER not defined'
-  return 1
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${FORTRAN_COMPILER}" ]; then
-  echo 'ERROR FORTRAN_COMPILER not defined'
-  return 1
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${PYTHON3}" ]; then
-  echo 'ERROR PYTHON3 not defined'
+  echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
   return 1
 fi
 
@@ -24,64 +24,65 @@ fi
 # ------------------------- COMPILE PLANCK LIKELIHOOD ------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
-
 if [ -z "${IGNORE_PLANCK_COMPILATION}" ]; then
-  if [ -n "${CLIK_PATH}" ]; then
-      export OLD_CLIK_PATH=$CLIK_PATH
+  echo 'COMPILING PLANCK'
+
+  if [ -z "${DEBUG_PLANCK_OUTPUT}" ]; then
+    export OUTPUT_PLANCK_1="/dev/null"
+    export OUTPUT_PLANCK_2="/dev/null"
+  else
+    export OUTPUT_PLANCK_1="/dev/tty"
+    export OUTPUT_PLANCK_2="/dev/tty"
+  fi
+  
+  if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
+    export CFITSLIBS=$ROOTDIR/.local/lib
+  else
+    export CFITSLIBS=$GLOBAL_PACKAGES_LOCATION
+  fi
+  
+  if [ -z "${IGNORE_FORTRAN_INSTALLATION}" ]; then
+    export LAPALIBS=$ROOTDIR/.local
+  else
+    export LAPALIBS=$GLOBAL_PACKAGES_LOCATION
   fi
 
-  if [ -n "${CLIK_DATA}" ]; then
-      export OLD_CLIK_DATA=$CLIK_DATA
+  if [ -z "${USE_SPT_CLIK_PLANCK}" ]; then
+    cd $ROOTDIR/external_modules/code/planck/code/plc_3.0/plc-3.1/
+  else
+    cd $ROOTDIR/external_modules/code/planck/code/spt_clik/
   fi
-
-  if [ -n "${CLIK_PLUGIN}" ]; then
-      export OLD_CLIK_PLUGIN=$CLIK_PLUGIN
-  fi
-
-  cd $ROOTDIR/external_modules/code/planck/code/plc_3.0/plc-3.1/
   
   rm -rf .waf*
 
-  $PYTHON3 waf distclean
-
-  if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
-    if [ $? -ne 0 ] 
-    then
-      echo "PROBLEM CONF PLANCK"
-    fi
-    if [ -z "${IGNORE_FORTRAN_INSTALLATION}" ]; then
-      FC=$FORTRAN_COMPILER CC=$C_COMPILER CXX=$CXX_COMPILER $PYTHON3 waf configure --gcc --gfortran --cfitsio_islocal --prefix $ROOTDIR/.local --lapack_prefix=$ROOTDIR/.local --cfitsio_lib=$ROOTDIR/.local/lib --python=$ROOTDIR/.local/bin/python
-      if [ $? -ne 0 ] 
-      then
-        echo "PROBLEM CONF PLANCK"
-      fi
-    else
-      FC=$FORTRAN_COMPILER CC=$C_COMPILER CXX=$CXX_COMPILER $PYTHON3 waf configure --gcc --gfortran --cfitsio_islocal --prefix $ROOTDIR/.local --lapack_prefix=$GLOBAL_PACKAGES_LOCATION --cfitsio_lib=$ROOTDIR/.local/lib --python=$ROOTDIR/.local/bin/python
-      if [ $? -ne 0 ] 
-      then
-        echo "PROBLEM CONF PLANCK"
-      fi
-    fi
+  $PYTHON3 waf distclean > ${OUTPUT_PLANCK_1} 2> ${OUTPUT_PLANCK_2}
+  if [ $? -ne 0 ]; then
+    echo "PLANCK COULD NOT RUN WAF DISTCLEAN"
+    cd $ROOTDIR
+    return 1
   else
-    if [ -z "${IGNORE_FORTRAN_INSTALLATION}" ]; then
-      FC=$FORTRAN_COMPILER CC=$C_COMPILER CXX=$CXX_COMPILER $PYTHON3 waf configure --gcc --gfortran --cfitsio_islocal --prefix $ROOTDIR/.local --lapack_prefix=$ROOTDIR/.local --cfitsio_prefix=$GLOBAL_PACKAGES_LOCATION --python=$ROOTDIR/.local/bin/python
-      if [ $? -ne 0 ] 
-      then
-        echo "PROBLEM CONF PLANCK"
-      fi
-    else
-      FC=$FORTRAN_COMPILER CC=$C_COMPILER CXX=$CXX_COMPILER $PYTHON3 waf configure --gcc --gfortran --cfitsio_islocal --prefix $ROOTDIR/.local --lapack_prefix=$GLOBAL_PACKAGES_LOCATION --cfitsio_prefix=$GLOBAL_PACKAGES_LOCATION --python=$ROOTDIR/.local/bin/python
-      if [ $? -ne 0 ] 
-      then
-        echo "PROBLEM CONF PLANCK"
-      fi
-    fi
+    echo "PLANCK WAF CLEAN RUN DONE"
   fi
-
-  $PYTHON3 waf install -v
-  if [ $? -ne 0 ] 
-  then
-    echo "PROBLEM INSTALLING PLANCK"
+  
+  FC=$FORTRAN_COMPILER CC=$C_COMPILER CXX=$CXX_COMPILER $PYTHON3 waf configure \
+    --gcc --gfortran --cfitsio_islocal --prefix $ROOTDIR/.local \
+    --lapack_prefix=${LAPALIBS} --cfitsio_lib=${CFITSLIBS} \
+    --python=${PYTHON3} > ${OUTPUT_PLANCK_1} 2> ${OUTPUT_PLANCK_2}
+  if [ $? -ne 0 ]; then
+    echo "PLANCK COULD NOT RUN WAF CONFIGURE"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "PLANCK WAF CONFIGURE RUN DONE"
+  fi
+  
+  $PYTHON3 waf install -v > ${OUTPUT_PLANCK_1} 2> ${OUTPUT_PLANCK_2}
+  if [ $? -ne 0 ]; then
+    echo "PLANCK COULD NOT RUN WAF INSTALL"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "PLANCK WAF INSTALL RUN DONE"
   fi
 
   cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/compile_polychord b/Cocoa/installation_scripts/compile_polychord
--- a/Cocoa/installation_scripts/compile_polychord
+++ b/Cocoa/installation_scripts/compile_polychord
@@ -1,26 +1,26 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return
-fi
-if [ -z "${PYTHON3}" ]; then
-    echo 'ERROR PYTHON3 not defined'
-    return
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR FORTRAN_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${PYTHON3}" ]; then
+    echo 'ERROR ENV VARIABLE PYTHON3 IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
+    return 1
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -29,20 +29,57 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_POLYCHORD_COMPILATION}" ]; then
-    cd $ROOTDIR/external_modules/code/PolyChordLite/
+  echo 'COMPILING POLYCHORD'
+  
+  cd $ROOTDIR/external_modules/code/PolyChordLite/
 
-    make clean
-    rm -rf ./lib/*.a
-    rm -rf ./lib/*.so
+  if [ -z "${DEBUG_POLY_OUTPUT}" ]; then
+    export OUTPUT_POLY_1="/dev/null"
+    export OUTPUT_POLY_2="/dev/null"
+  else
+    export OUTPUT_POLY_1="/dev/tty"
+    export OUTPUT_POLY_2="/dev/tty"
+  fi
 
-    make all MPI=1 COMPILER_TYPE=gnu
-    make -j $MAKE_NUM_THREADS pypolychord MPI=1
-
-    CC=$MPI_CC_COMPILER CXX=$MPI_CXX_COMPILER $PYTHON3 setup.py install --prefix $ROOTDIR/.local
-    if [ $? -ne 0 ] 
-    then
-      echo "PROBLEM INSTALLING POLYCHORD"
-    fi
-
+  make clean > ${OUTPUT_POLY_1} 2> ${OUTPUT_POLY_2}
+  if [ $? -ne 0 ]; then
+    echo "POLYCHORD COULD NOT RUN MAKE CLEAN"
     cd $ROOTDIR
+    return 1
+  else
+    echo "POLYCHORD MAKE CLEAN DONE"
+  fi
+
+  rm -rf ./lib/*.a
+  rm -rf ./lib/*.so
+
+  make all  > ${OUTPUT_POLY_1} 2> ${OUTPUT_POLY_2}
+  if [ $? -ne 0 ]; then
+    echo "POLYCHORD COULD NOT RUN MAKE ALL"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "POLYCHORD MAKE ALL RUN DONE"
+  fi
+
+  make -j $MAKE_NUM_THREADS pypolychord > ${OUTPUT_POLY_1} 2> ${OUTPUT_POLY_2}
+  if [ $? -ne 0 ]; then
+    echo "POLYCHORD COULD NOT RUN MAKE PYPOLYCHORD"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "POLYCHORD MAKE CLEAN PYPOLYCHORD RUN DONE"
+  fi
+
+  CC=$MPI_CC_COMPILER CXX=$MPI_CXX_COMPILER $PYTHON3 setup.py install \
+      --prefix $ROOTDIR/.local  > ${OUTPUT_POLY_1} 2> ${OUTPUT_POLY_2}
+  if [ $? -ne 0 ]; then
+    echo "POLYCHORD COULD NOT RUN PYTHON3 SETUP.PY INSTALL"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "POLYCHORD PYTHON3 SETUP.PY INSTALL RUN DONE"
+  fi
+
+  cd $ROOTDIR
 fi
diff --git a/Cocoa/installation_scripts/setup_binutils b/Cocoa/installation_scripts/setup_binutils
--- a/Cocoa/installation_scripts/setup_binutils
+++ b/Cocoa/installation_scripts/setup_binutils
@@ -1,19 +1,28 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${CMAKE}" ]; then
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
+    return 1
 fi
+
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------- DISTUTILS LIBRARY  ----------------------------
@@ -21,23 +30,111 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_DISTUTILS_INSTALLATION}" ]; then
-    echo 'INSTALLING DISTUTILS - THAT WILL TAKE A WHILE'
+  echo 'INSTALLING TEXINFO - THAT WILL TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/texinfo-6.7
+  cd $ROOTDIR/../cocoa_installation_libraries/texinfo-6.7
 
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+  if [ -z "${DEBUG_DISTUTILS_PACKAGE}" ]; then
+    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --disable-perl-xs \
+      > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "TEXINFO CONFIGURE RUN DONE"
+    else
+      echo "TEXINFO COULD NOT RUN CONFIGURE" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "TEXINFO MAKE RUN DONE"
+    else
+      echo "TEXINFO COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "TEXINFO MAKE INSTALL RUN DONE"
+    else
+      echo "TEXINFO COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --disable-perl-xs --prefix=$ROOTDIR/.local
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
 
-    cd $ROOTDIR/../cocoa_installation_libraries/binutils-2.37
+    make
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
 
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
+  fi
+
+  # ----------------------------------------------------------------------------------------
+  # ----------------------------------------------------------------------------------------
+  # ----------------------------------------------------------------------------------------
+  echo 'INSTALLING BINUTILS - THAT WILL TAKE A WHILE'
+
+  cd $ROOTDIR/../cocoa_installation_libraries/binutils-2.37
+
+  if [ -z "${DEBUG_DISTUTILS_PACKAGE}" ]; then
     FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "BINUTILS CONFIGURE RUN DONE"
+    else
+      echo "BINUTILS COULD NOT RUN CONFIGURE" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "BINUTILS MAKE RUN DONE"
+    else
+      echo "BINUTILS COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "BINUTILS MAKE INSTALL RUN DONE"
+    else
+      echo "BINUTILS COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --disable-perl-xs
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
 
-    cd $ROOTDIR/
+    make
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR/
 fi
diff --git a/Cocoa/installation_scripts/setup_c_packages b/Cocoa/installation_scripts/setup_c_packages
--- a/Cocoa/installation_scripts/setup_c_packages
+++ b/Cocoa/installation_scripts/setup_c_packages
@@ -1,113 +1,248 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# -------------------------------- C PACKAGES --------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
 
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# ------------------------------------- C PACKAGES -------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+
+# --------------------------------------------------------------------------------------
+# ---------------------------------------- FFTW ----------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
-    echo 'INSTALLING C FFTW - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING C FFTW LIBRARY - THIS MIGHT TAKE A WHILE'
 
+  if [ -z "${FFTW_NEW_VERSION}" ]; then
     cd $ROOTDIR/../cocoa_installation_libraries/fftw-3.3.8
+  else
+    cd $ROOTDIR/../cocoa_installation_libraries/fftw-3.3.10
+  fi
 
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
+  if [ -z "${DEBUG_C_PACKAGES}" ]; then
+    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
+    --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "FFTW CONFIGURE RUN DONE"
+    else
+      echo "FFTW COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE FFTW OK"
+    if [ $? -eq 0 ]; then
+      echo "FFTW MAKE RUN DONE"
     else
-      echo "FFTW COULD NOT MAKE" >&2
+      echo "FFTW COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL FFTW OK"
+    if [ $? -eq 0 ]; then
+      echo "FFTW MAKE INSTALL RUN DONE"
     else
-      echo "FFTW COULD NOT MAKE INSTALL" >&2
+      echo "FFTW COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
+    --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------- CFITSIO --------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
-    echo 'INSTALLING C CFITSIO - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING C CFITSIO LIBRARY - THIS MIGHT TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/cfitsio-3.47
+  cd $ROOTDIR/../cocoa_installation_libraries/cfitsio-3.47
 
-    rm -f CMakeCache.txt
+  rm -f CMakeCache.txt
 
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR .  > /dev/null 2> /dev/null
+  if [ -z "${DEBUG_C_PACKAGES}" ]; then
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR .  > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "CFITSIO CMAKE RUN DONE"
+    else
+      echo "CFITSIO COULD NOT RUN CMAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE CFITSIO OK"
+    if [ $? -eq 0 ]; then
+      echo "CFITSIO MAKE RUN DONE"
     else
-      echo "CFITSIO COULD NOT MAKE" >&2
+      echo "CFITSIO COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL CFITSIO OK"
+    if [ $? -eq 0 ]; then
+      echo "CFITSIO MAKE INSTALL RUN DONE"
     else
-      echo "CFITSIO COULD NOT MAKE INSTALL" >&2
+      echo "CFITSIO COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# ----------------------------------------- GSL ----------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
-    echo 'INSTALLING C GSL - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING C GSL LIBRARY - THIS MIGHT TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/gsl-2.7/
+  cd $ROOTDIR/../cocoa_installation_libraries/gsl-2.7/
 
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+  if [ -z "${DEBUG_C_PACKAGES}" ]; then
+    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
+    --enable-static=yes > /dev/null 2> /dev/null
     if [ $? -eq 0 ] 
     then
-      echo "MAKE GSL OK"
+      echo "GSL CONFIGURE RUN DONE"
     else
-      echo "GSL COULD NOT MAKE" >&2
+      echo "GSL COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "GSL MAKE RUN DONE"
+    else
+      echo "GSL COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
+    if [ $? -eq 0 ]; then
       echo "MAKE INSTALL GSL OK"
     else
-      echo "GSL COULD NOT MAKE INSTALL" >&2
+      echo "GSL COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
+    --enable-static=yes
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# ----------------------------------- EUCLID EMU ---------------------------------------
+# --------------------------------------------------------------------------------------
+
+if [ -z "${DEBUG_PIP_OUTPUT}" ]; then
+  export OUTPUT_PIP_1="/dev/null"
+  export OUTPUT_PIP_2="/dev/null"
+else
+  export OUTPUT_PIP_1="/dev/tty"
+  export OUTPUT_PIP_2="/dev/tty"
+fi
+
+# WE MIGRATED euclidemu2 TO setup_c_packages SCRIPT BECAUSE IT DEPENDS ON GSL-GNU LIB
+env CXX=$CXX_COMPILER CC=$C_COMPILER  $PIP3 install --global-option=build_ext \
+  $ROOTDIR/../cocoa_installation_libraries/euclidemu2-1.2.0 --no-dependencies \
+  --prefix=$ROOTDIR/.local --no-index > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
+if [ $? -ne 0 ]; then
+  echo "PROBLEM PIP euclidemul"
+  return 1
+else
+  echo "PIP euclidemul DONE"
+fi
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
diff --git a/Cocoa/installation_scripts/setup_cmake b/Cocoa/installation_scripts/setup_cmake
--- a/Cocoa/installation_scripts/setup_cmake
+++ b/Cocoa/installation_scripts/setup_cmake
@@ -1,17 +1,21 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
 # ----------------------------------------------------------------------------
@@ -21,36 +25,56 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_CMAKE_INSTALLATION}" ]; then
-    echo 'INSTALLING CMAKE - THAT WILL TAKE A WHILE'
+  echo 'INSTALLING CMAKE - THAT WILL TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/cmake-3.17.1
+  cd $ROOTDIR/../cocoa_installation_libraries/cmake-3.17.1
 
+  if [ -z "${DEBUG_CMAKE_PACKAGE}" ]; then
     env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "BOOTSTRAP CMAKE OK"
+    if [ $? -eq 0 ]; then
+      echo "CMAKE BOOTSTRAP RUN DONE"
     else
-      echo "CMAKE COULD NOT BOOTSTRAP" >&2
+      echo "CMAKE COULD NOT RUN BOOTSTRAP" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE CMAKE OK"
+    if [ $? -eq 0 ]; then
+      echo "CMAKE MAKE RUN DONE"
     else
-      echo "CMAKE COULD NOT MAKE" >&2
+      echo "CMAKE COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL CMAKE OK"
+    if [ $? -eq 0 ]; then
+      echo "CMAKE MAKE INSTALL RUN DONE"
     else
-      echo "CMAKE COULD NOT MAKE INSTALL" >&2
+      echo "CMAKE COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
diff --git a/Cocoa/installation_scripts/setup_cpp_packages b/Cocoa/installation_scripts/setup_cpp_packages
--- a/Cocoa/installation_scripts/setup_cpp_packages
+++ b/Cocoa/installation_scripts/setup_cpp_packages
@@ -1,145 +1,226 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ------------------------------- C++ PACKAGES -------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
 
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# ------------------------------------ C++ PACKAGES ------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------- SPDLOG ---------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
-    echo 'INSTALLING CPP SPDLOG - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING CPP SPDLOG LIBRARY - THIS MIGHT TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/spdlog
+  cd $ROOTDIR/../cocoa_installation_libraries/spdlog
 
-    rm -f CMakeCache.txt
+  rm -f CMakeCache.txt
 
-    $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "CMAKE SPDLOG OK"
+  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
+    $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
+    -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
+    if [ $? -eq 0 ];then
+      echo "SPDLOG CMAKE RUN DONE"
     else
-      echo "SPDLOG COULD NOT CMAKE" >&2
+      echo "SPDLOG COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE SPDLOG OK"
+    if [ $? -eq 0 ]; then
+      echo "SPDLOG MAKE RUN DONE"
     else
-      echo "SPDLOG COULD NOT MAKE" >&2
+      echo "SPDLOG COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL SPDLOG OK"
+    if [ $? -eq 0 ]; then
+      echo "SPDLOG MAKE INSTALL RUN DONE"
     else
-      echo "SPDLOG COULD NOT MAKE INSTALL" >&2
+      echo "SPDLOG COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
+    -DCMAKE_CXX_COMPILER=$CXX_COMPILER .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make 
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# ------------------------------------- ARMADILLO --------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
-    echo 'INSTALLING CPP ARMADILLO - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING CPP ARMADILLO LIBRARY - THIS MIGHT TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/armadillo-10.6.2
+  cd $ROOTDIR/../cocoa_installation_libraries/armadillo-10.6.2
 
-    rm -f CMakeCache.txt
+  rm -f CMakeCache.txt
 
+  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
     -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
     -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
     -DBLAS_FOUND=NO --log-level=ERROR . > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "CMAKE ARMA OK"
+    if [ $? -eq 0 ]; then
+      echo "ARMADILLO CMAKE RUN DONE"
     else
-      echo "ARMA COULD NOT CMAKE" >&2
+      echo "ARMADILLO COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
+
     make clean
     make -j $MAKE_NUM_THREADS all -Wno-dev > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE ARMA OK"
+    if [ $? -eq 0 ]; then
+      echo "ARMADILLO MAKE RUN DONE"
     else
-      echo "ARMA COULD NOT MAKE" >&2
+      echo "ARMADILLO COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL ARMA OK"
+    if [ $? -eq 0 ]; then
+      echo "ARMADILLO MAKE INSTALL RUN DONE"
     else
-      echo "ARMA COULD NOT MAKE INSTALL" >&2
+      echo "ARMADILLO COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+      -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+      -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
+      -DBLAS_FOUND=NO .
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
 
-    cd $ROOTDIR
+    make clean
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    make install 
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# --------------------------- CARMA (ARMADILLO <-> PYBIND11) ---------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_CARMA_INSTALLATION}" ]; then
-    echo 'INSTALLING CARMA -  THE PYTHON <-> ARMADILLO CONVERSION - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING CARMA -  THE PYTHON <-> ARMADILLO CONVERSION - THIS MIGHT TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/carma
+  cd $ROOTDIR/../cocoa_installation_libraries/carma
 
-    rm -rf $ROOTDIR/.local/include/carma/
-    
-    mkdir $ROOTDIR/.local/include/carma/ 
+  rm -rf $ROOTDIR/.local/include/carma/
+  
+  mkdir $ROOTDIR/.local/include/carma/ 
 
-    cp ./carma.h $ROOTDIR/.local/include/
+  cp ./carma.h $ROOTDIR/.local/include/
 
-    cp -r ./carma_bits $ROOTDIR/.local/include/
+  cp -r ./carma_bits $ROOTDIR/.local/include/
 
-    cd $ROOTDIR
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# ---------------------------------------- BOOST ---------------------------------------
+# --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
-    echo 'INSTALLING CPP BOOST - THAT WILL TAKE A WHILE'
+  echo 'INSTALLING CPP BOOST LIBRARY - THIS WILL TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/boost_1_72_0/
+  cd $ROOTDIR/../cocoa_installation_libraries/boost_1_72_0/
 
+  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
     ./bootstrap.sh --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "bootstrap BOOST OK"
+    if [ $? -eq 0 ]; then
+      echo "BOOST BOOTSTRAP RUN DONE"
     else
-      echo "BOOST COULD NOT bootstrap" >&2
+      echo "BOOST COULD NOT RUN BOOTSTRAP - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
       return 1
     fi
 
-    ./b2 --with=regex install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "B2 BOOST OK"
+    ./b2 --with=regex install --without-python --without-thread \
+    --without-timer --without-mpi --without-atomic > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "BOOST B2 RUN DONE"
     else
-      echo "BOOST COULD NOT B2" >&2
+      echo "BOOST COULD NOT RUN B2 - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      return 1
+    fi
+  else
+    ./bootstrap.sh --prefix=$ROOTDIR/.local 
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
       return 1
     fi
     
-    cd $ROOTDIR
+    ./b2 --with=regex install --without-python --without-thread \
+    --without-timer --without-mpi --without-atomic
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+  
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
diff --git a/Cocoa/installation_scripts/setup_fortran_packages b/Cocoa/installation_scripts/setup_fortran_packages
--- a/Cocoa/installation_scripts/setup_fortran_packages
+++ b/Cocoa/installation_scripts/setup_fortran_packages
@@ -1,72 +1,97 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return 1
-fi
-if [ -z "${FORTRAN_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CMAKE}" ]; then
-    echo 'ERROR CMAKE not defined'
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------- FORTRAN PACKAGES -----------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
 
-if [ -z "${IGNORE_FORTRAN_INSTALLATION}" ]; then
-   if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
-        echo 'INSTALLING FORTRAN LAPACK - THAT MIGHT TAKE A WHILE'
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# ---------------------------------- FORTRAN PACKAGES ----------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
 
-        cd $ROOTDIR/../cocoa_installation_libraries/
+if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
+  echo 'INSTALLING FORTRAN LAPACK - THIS MIGHT TAKE A WHILE'
 
-        rm -rf lapack-build
-        mkdir lapack-build
+  cd $ROOTDIR/../cocoa_installation_libraries/
 
-        cd ./lapack-build
+  rm -rf lapack-build
+  mkdir lapack-build
 
-        $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../lapack-3.9.0/ > /dev/null 2> /dev/null
-        
-        if [ $? -eq 0 ] 
-        then
-          echo "CMAKE LAPACK OK"
-        else
-          echo "LAPACK COULD NOT CMAKE" >&2
-          return 1
-        fi
+  cd ./lapack-build
 
-        make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-        if [ $? -eq 0 ] 
-        then
-          echo "MAKE LAPACK OK"
-        else
-          echo "LAPACK COULD NOT MAKE" >&2
-          return 1
-        fi
-
-        make install > /dev/null 2> /dev/null
-        if [ $? -eq 0 ] 
-        then
-          echo "MAKE INSTALL LAPACK OK"
-        else
-          echo "LAPACK COULD NOT MAKE INSTALL" >&2
-          return 1
-        fi
-
-        cd $ROOTDIR
+  if [ -z "${DEBUG_FORTRAN_PACKAGES}" ]; then
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../lapack-3.9.0/ > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "LAPACK CMAKE RUN DONE"
+    else
+      echo "LAPACK COULD NOT RUN CMAKE" >&2
+      cd $ROOTDIR
+      return 1
     fi
+
+    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "LAPACK MAKE RUN DONE"
+    else
+      echo "LAPACK COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "LAPACK MAKE INSTALL RUN DONE"
+    else
+      echo "LAPACK COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../lapack-3.9.0/
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi
+  fi
+  
+  cd $ROOTDIR
 fi
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
diff --git a/Cocoa/installation_scripts/setup_openblas b/Cocoa/installation_scripts/setup_openblas
--- a/Cocoa/installation_scripts/setup_openblas
+++ b/Cocoa/installation_scripts/setup_openblas
@@ -1,19 +1,28 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${CMAKE}" ]; then
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE FORTRAN_COMPILER IS NOT DEFINED' >&2
     return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
-    echo 'ERROR MAKE_NUM_THREADS not defined'
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
     return 1
 fi
+
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------- OPENBLAS LIBRARY  ----------------------------
@@ -21,30 +30,44 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_OPENBLAS_INSTALLATION}" ]; then
-    echo 'INSTALLING OPENBLAS - THAT WILL TAKE A WHILE'
+  echo 'INSTALLING OPENBLAS - THAT WILL TAKE A WHILE'
 
-    cd $ROOTDIR/../cocoa_installation_libraries/OpenBLAS
+  cd $ROOTDIR/../cocoa_installation_libraries/OpenBLAS
 
-    export MAKE_NB_JOBS=$MAKE_NUM_THREADS
-    
+  export MAKE_NB_JOBS=$MAKE_NUM_THREADS
+  make clean > /dev/null 2> /dev/null
+
+  if [ -z "${DEBUG_OPENBLAS_PACKAGE}" ]; then
     make CC=$C_COMPILER FC=$FORTRAN_COMPILER USE_OPENMP=1 > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE OPENBLAS OK"
+    if [ $? -eq 0 ]; then
+      echo "OPENBLAS MAKE RUN DONE"
     else
-      echo "OPENBLAS COULD NOT MAKE" >&2
+      echo "OPENBLAS COULD NOT RUN MAKE" >&2
       return 1
     fi
 
     make install PREFIX=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL OPENBLAS OK"
+    if [ $? -eq 0 ]; then
+      echo "OPENBLAS MAKE INSTALL RUN DONE"
     else
-      echo "OPENBLAS COULD NOT MAKE INSTALL" >&2
+      echo "OPENBLAS COULD NOT RUN MAKE INSTALL" >&2
       return 1
     fi
-    unset MAKE_NB_JOBS
+  else
+    make CC=$C_COMPILER FC=$FORTRAN_COMPILER USE_OPENMP=1
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
+    
+    make install PREFIX=$ROOTDIR/.local
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
+  fi
 
-    cd $ROOTDIR/
+  unset MAKE_NB_JOBS
+
+  cd $ROOTDIR/
 fi
diff --git a/Cocoa/installation_scripts/setup_xz b/Cocoa/installation_scripts/setup_xz
--- a/Cocoa/installation_scripts/setup_xz
+++ b/Cocoa/installation_scripts/setup_xz
@@ -1,15 +1,28 @@
 if [ -z "${ROOTDIR}" ]; then
-    echo 'ERROR ROOTDIR not defined'
-    return
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
-    echo 'ERROR CXX_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE CXX_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
-    echo 'ERROR C_COMPILER not defined'
-    return
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
 fi
+if [ -z "${CMAKE}" ]; then
+    echo 'ERROR ENV VARIABLE MAKE IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${FORTRAN_COMPILER}" ]; then
+    echo 'ERROR ENV VARIABLE C_COMPILER IS NOT DEFINED' >&2
+    return 1
+fi
+if [ -z "${MAKE_NUM_THREADS}" ]; then
+    echo 'ERROR ENV VARIABLE MAKE_NUM_THREADS IS NOT DEFINED' >&2
+    return 1
+fi
+
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # -------------------------- XZ COMPRESSION Library --------------------------
@@ -17,34 +30,63 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_XZ_INSTALLATION}" ]; then
-    echo 'INSTALLING XZ LIBRARY - THAT MIGHT TAKE A WHILE'
+  echo 'INSTALLING XZ LIBRARY - THAT MIGHT TAKE A WHILE'
 
-    cd ../cocoa_installation_libraries/
+  cd ../cocoa_installation_libraries/
 
-    #False xz file: just to trigger GIT LFS
-    cp xz-5.2.5.tar.gz.xz xz-5.2.5.tar.gz
+  #False xz file: just to trigger GIT LFS
+  cp xz-5.2.5.tar.gz.xz xz-5.2.5.tar.gz
 
-    tar -xf xz-5.2.5.tar.gz.xz
+  tar -xf xz-5.2.5.tar.gz.xz
 
-    cd ./xz-5.2.5/
+  cd ./xz-5.2.5/
 
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null
-
-    make -j $MAKE_NUM_THREADS all > /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE XZ OK"
+  if [ -z "${DEBUG_XZ_PACKAGE}" ]; then
+    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "XZ CONFIGURE RUN DONE"
     else
-      echo "XZ COULD NOT MAKE" >&2
+      echo "XZ COULD NOT RUN CONFIGURE" >&2
+      cd $ROOTDIR
+      return 1
     fi
 
-    make install > /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "MAKE INSTALL XZ OK"
+    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "XZ MAKE RUN DONE"
     else
-      echo "XZ COULD NOT MAKE INSTALL" >&2
+      echo "XZ COULD NOT RUN MAKE" >&2
+      cd $ROOTDIR
+      return 1
     fi
 
-    cd ../../Cocoa
+    make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ]; then
+      echo "XZ MAKE INSTALL RUN DONE"
+    else
+      echo "XZ COULD NOT RUN MAKE INSTALL" >&2
+      cd $ROOTDIR
+      return 1
+    fi
+  else
+    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
+
+    make all
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi  
+        
+    make install
+    if [ $? -ne 0 ];then
+      cd $ROOTDIR
+      return 1
+    fi 
+  fi
+
+  cd $ROOTDIR
 fi
diff --git a/Cocoa/start_cocoa b/Cocoa/start_cocoa
--- a/Cocoa/start_cocoa
+++ b/Cocoa/start_cocoa
@@ -17,84 +17,138 @@ function addvar () {
 }
 
 if [ -n "${OMP_NUM_THREADS}" ]; then
-  export OLD_OMP_NUM_THREADS=$OMP_NUM_THREADS
+    export OLD_OMP_NUM_THREADS=$OMP_NUM_THREADS
+else
+    export OLD_OMP_NUM_THREADS="x"
 fi
 
 if [ -n "${LD_LIBRARY_PATH}" ]; then
-  export OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
+    export OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
+else
+    # -n fails if string is null
+    export OLD_LD_LIBRARY_PATH="x"
 fi
 
 if [ -n "${PYTHONPATH}" ]; then
-  export OLD_PYTHONPATH=$PYTHONPATH
+    export OLD_PYTHONPATH=$PYTHONPATH
+else
+    export OLD_PYTHONPATH="x"
 fi
 
 if [ -n "${PATH}" ]; then
-  export OLD_PATH=$PATH
+    export OLD_PATH=$PATH
+else
+    export OLD_PATH="x"
 fi
 
 if [ -n "${C_INCLUDE_PATH}" ]; then
-  export OLD_C_INCLUDE_PATH=$C_INCLUDE_PATH
+    export OLD_C_INCLUDE_PATH=$C_INCLUDE_PATH
+else
+    export OLD_C_INCLUDE_PATH="x"
 fi
 
 if [ -n "${CPLUS_INCLUDE_PATH}" ]; then
-  export OLD_CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH
+    export OLD_CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH
+else
+    export OLD_CPLUS_INCLUDE_PATH="x"
 fi
 
 if [ -n "${LDFLAGS}" ]; then
-  export OLD_LDFLAGS=$LDFLAGS
+    export OLD_LDFLAGS=$LDFLAGS
+else
+    export OLD_LDFLAGS="x"
 fi
 
 if [ -n "${CPATH}" ]; then
-  export OLD_CPATH=$CPATH
+    export OLD_CPATH=$CPATH
+else
+    export OLD_CPATH="x"
 fi
 
 if [ -n "${LD_RUN_PATH}" ]; then
     export OLD_LD_RUN_PATH=$LD_RUN_PATH
+else
+    export OLD_LD_RUN_PATH="x"
 fi
 
 if [ -n "${CMAKE_LIBRARY_PATH}" ]; then
     export OLD_CMAKE_LIBRARY_PATH=$CMAKE_LIBRARY_PATH
+else
+    export OLD_CMAKE_LIBRARY_PATH="x"
 fi
 
 if [ -n "${CMAKE_INCLUDE_PATH}" ]; then
     export OLD_CMAKE_INCLUDE_PATH=$CMAKE_INCLUDE_PATH
+else
+    export OLD_CMAKE_INCLUDE_PATH="x"
 fi
 
 if [ -n "${LIBRARY_PATH}" ]; then
     export OLD_LIBRARY_PATH=$LIBRARY_PATH
+else
+    export OLD_LIBRARY_PATH="x"
 fi
 
 if [ -n "${INCLUDEPATH}" ]; then
     export OLD_INCLUDEPATH=$INCLUDEPATH
+else
+    export OLD_INCLUDEPATH="x"
 fi
 
 if [ -n "${INCLUDE}" ]; then
     export OLD_INCLUDE=$INCLUDE
+else
+    export OLD_INCLUDE="x"
+fi
+
+if [ -n "${CPATH}" ]; then
+    export OLD_CPATH=$CPATH
+else
+    export OLD_CPATH="x"
 fi
 
 if [ -n "${NUMPY_HEADERS}" ]; then
-  export OLD_NUMPY_HEADERS=$NUMPY_HEADERS
+    export OLD_NUMPY_HEADERS=$NUMPY_HEADERS
+else
+    export OLD_NUMPY_HEADERS="x"
 fi
 
 if [ -n "${OBJC_INCLUDE_PATH}" ]; then
-  export OLD_OBJC_INCLUDE_PATH=$OBJC_INCLUDE_PATH
+    export OLD_OBJC_INCLUDE_PATH=$OBJC_INCLUDE_PATH
+else
+    export OLD_OBJC_INCLUDE_PATH="x"
 fi
 
 if [ -n "${OBJC_PATH}" ]; then
-  export OLD_OBJC_PATH=$OBJC_PATH
+    export OLD_OBJC_PATH=$OBJC_PATH
+else
+    export OLD_OBJC_PATH="x"
 fi
 
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
+if [ -n "${CFLAGS}" ]; then
+    export OLD_CFLAGS=$CFLAGS
+else
+    export OLD_CFLAGS="x"
+fi
+
+if [ -n "${INCLUDE_PATH}" ]; then
+    export OLD_INCLUDE_PATH=$INCLUDE_PATH
+else
+    export OLD_INCLUDE_PATH="x"
+fi
 
 if [ -n "${SET_INSTALLATION_OPTIONS}" ]; then
   source $SET_INSTALLATION_OPTIONS
 else
   source set_installation_options
 fi
-
+if [ -n "${MINICONDA_INSTALLATION}" ]; then
+  if [ ${CONDA_SHLVL} -ne 1 ]; then
+    echo "MINICONDA_INSTALLATION SET BUT CONDA ENVIRONMENT NOT ACTIVATED"
+    source stop_cocoa
+    return 1
+  fi
+fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ---------------------- Activate Virtual Enviroment -------------------------
@@ -102,41 +156,53 @@ fi
 # ----------------------------------------------------------------------------
 
 source $ROOTDIR/.local/bin/activate
+if [ $? -ne 0 ]; then
+  echo "COCOA PRIVATE PYTHON ENV ACTIVATION FAILED" >&2
+  echo "PLEASE RUN STOP_COCOA TO CLEN ENVIRONMENTAL FLAGS" >&2
+  return 1
+fi
 
 export PATH=$ROOTDIR/.local/bin:$PATH
 
-addvar PYTHONPATH $ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages
-addvar PYTHONPATH $ROOTDIR/.local/lib
+export CFLAGS="${CFLAGS} -I$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include"
+
+export LDFLAGS="${LDFLAGS} -L$ROOTDIR/.local/lib"
 
 export C_INCLUDE_PATH=$C_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
+
 export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
-export C_INCLUDE_PATH=$C_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include/numpy
-export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include/numpy
 
-export NUMPY_HEADERS=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
-export LD_LIBRARY_PATH=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/lib:$LD_LIBRARY_PATH
-export CPATH=$CPATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
-export CFLAGS=$CFLAGS:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
-export CPATH=$CPATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include/numpy
-export CFLAGS=$CFLAGS:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include/numpy
+export PYTHONPATH=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH
+export PYTHONPATH=$ROOTDIR/.local/lib:$PYTHONPATH
+export PYTHONPATH=$ROOTDIR/.local/lib/python/site-packages:$PYTHONPATH
 
-export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$ROOTDIR/.local/lib
-export LDFLAGS="-L$ROOTDIR/.local/lib":$LDFLAGS
 export LD_RUN_PATH=$ROOTDIR/.local/lib:$LD_RUN_PATH
+
 export LIBRARY_PATH=$ROOTDIR/.local/lib:$LIBRARY_PATH
 
 export CMAKE_INCLUDE_PATH=$ROOTDIR/.local/include/python${PYTHON_VERSION}m/:$CMAKE_INCLUDE_PATH
 export CMAKE_INCLUDE_PATH=$ROOTDIR/.local/include/:$CMAKE_INCLUDE_PATH    
+
 export CMAKE_LIBRARY_PATH=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages:$CMAKE_LIBRARY_PATH
 export CMAKE_LIBRARY_PATH=$ROOTDIR/.local/lib:$CMAKE_LIBRARY_PATH
 
 export INCLUDE_PATH=$ROOTDIR/.local/include/:$INCLUDE_PATH
+
 export INCLUDEPATH=$ROOTDIR/.local/include/:$INCLUDEPATH
+
 export INCLUDE=$ROOTDIR/.local/include/:$INCLUDE
+
+export CPATH=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include:$CPATH
 export CPATH=$ROOTDIR/.local/include/:$CPATH
 
 export OBJC_INCLUDE_PATH=$ROOTDIR/.local/:OBJC_INCLUDE_PATH
+
 export OBJC_PATH=$ROOTDIR/.local/:OBJC_PATH
+
+export LD_LIBRARY_PATH=$ROOTDIR/.local/lib:$LD_LIBRARY_PATH
+export LD_LIBRARY_PATH=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/lib
+
+export NUMPY_HEADERS=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
 
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -147,22 +213,22 @@ export OBJC_PATH=$ROOTDIR/.local/:OBJC_PATH
 if [ -z "${IGNORE_PLANCK_COMPILATION}" ]; then
   if [ -n "${CLIK_PATH}" ]; then
     export OLD_CLIK_PATH=$CLIK_PATH
+  else
+    export OLD_CLIK_PATH="x"
   fi
 
   if [ -n "${CLIK_DATA}" ]; then
     export OLD_CLIK_DATA=$CLIK_DATA
+  else
+    export OLD_CLIK_DATA="x"
   fi
 
   if [ -n "${CLIK_PLUGIN}" ]; then
     export OLD_CLIK_PLUGIN=$CLIK_PLUGIN
+  else
+    export OLD_CLIK_PLUGIN="x"
   fi
-
-  export PYTHONPATH=$ROOTDIR/.local/lib/python/site-packages:$PYTHONPATH
-
-  if [ -n "${GLOBAL_PACKAGES_LOCATION}" ]; then
-    export PYTHONPATH=$GLOBAL_PACKAGES_LOCATION/lib/python$PYTHON_VERSION/site-packages:$PYTHONPATH
-  fi
-
+  
   export CLIK_PATH=$ROOTDIR/.local
 
   export CLIK_DATA=$ROOTDIR/.local/share/clik
@@ -182,4 +248,5 @@ source $ROOTDIR/projects/start_all.sh
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+
 export START_COCOA_DONE=1
diff --git a/cocoa_installation_libraries/clean_all b/cocoa_installation_libraries/clean_all
--- a/cocoa_installation_libraries/clean_all
+++ b/cocoa_installation_libraries/clean_all
@@ -1,3 +1,12 @@
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
+fi
+
+cd ${ROOTDIR}/../cocoa_installation_libraries
+
+echo 'CLEAN ALL INSTALLATION LIBRARIES - THAT MIGHT TAKE A WHILE'
+
 rm -rf ./armadillo-10.6.2
 
 rm -rf ./binutils-2.34
@@ -11,6 +20,9 @@ rm -rf ./cmake-3.17.1
 rm -rf ./carma
 
 rm -rf ./fftw-3.3.8
+rm -rf ./fftw-3.3.10/
+
+rm -rf ./gsl-2.6
 
 rm -rf ./gsl-2.7
 
@@ -20,13 +32,23 @@ rm -rf ./lapack-build
 
 rm -rf ./OpenBLAS
 
-rm -rf  ./pip_cache
+rm -rf ./pip_cache
 
 rm -rf ./spdlog
 
 rm -rf ./texinfo-6.7
 
 rm -rf ./xz-5.2.5
+rm -f ./xz-5.2.5.tar.gz
 
 rm -rf ./expat241
 
+rm -rf ./cocoa_build
+
+rm -rf ./CMake-hdf5-1.10.10
+
+rm -rf ./binutils-2.37
+
+echo 'CLEAN ALL INSTALLATION LIBRARIES DONE'
+
+cd ${ROOTDIR}
