Update

diff --git a/Cocoa/clean_all b/Cocoa/clean_all
--- a/Cocoa/clean_all
+++ b/Cocoa/clean_all
@@ -2,10 +2,9 @@ if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
 if [ -z "${IGNORE_CAMB_COMPILATION}" ]; then
     source $ROOTDIR/installation_scripts/clean_camb
     source $ROOTDIR/installation_scripts/clean_cambede
@@ -19,10 +18,9 @@ fi
 if [ -z "${IGNORE_POLYCHORD_COMPILATION}" ]; then
     source $ROOTDIR/installation_scripts/clean_polychord
 fi
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
 if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
@@ -38,16 +36,29 @@ find . -maxdepth 12 -name '*.a' -delete
 
 cd $ROOTDIR/external_modules/data
 sh clean_all.sh
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
-# --------------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
 if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
     return 1
 fi
 
 source $ROOTDIR/../cocoa_installation_libraries/clean_all
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+if [ -z "${ROOTDIR}" ]; then
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
+fi
+rm -rf $ROOTDIR/cobaya/
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
 cd $ROOTDIR
 source stop_cocoa
 rm -rf ./.local/
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
+# ------------------------------------------------------------------------------
diff --git a/Cocoa/setup_cocoa_installation_packages b/Cocoa/setup_cocoa_installation_packages
--- a/Cocoa/setup_cocoa_installation_packages
+++ b/Cocoa/setup_cocoa_installation_packages
@@ -220,9 +220,8 @@ export NUMPY_HEADERS=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/num
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 
-
 if [ -z "${MINICONDA_INSTALLATION}" ]; then
-  source ./installation_scripts/setup_xz
+  source $ROOTDIR/installation_scripts/setup_xz
   if [ $? -ne 0 ]; then
     echo  -e '\033[0;31m'"SCRIPT setup_xz FAILED"'\033[0m'
     cd $ROOTDIR
@@ -238,10 +237,9 @@ if [ $? -ne 0 ]; then
   source stop_cocoa
   return 1
 fi
-
   
 if [ -z "${DEBUG_SKIP_FILE_DECOMPRESSION_SETUP_COCOA}" ]; then
-  source ./installation_scripts/setup_decompress_files
+  source $ROOTDIR/installation_scripts/setup_decompress_files
   if [ $? -ne 0 ]; then
     echo  -e '\033[0;31m'"SCRIPT setup_decompress_files FAILED"'\033[0m'
     cd $ROOTDIR
@@ -261,7 +259,7 @@ if [ -z "${MINICONDA_INSTALLATION}" ]; then
 fi
 
 if [ -z "${MINICONDA_INSTALLATION}" ]; then
-  source ./installation_scripts/setup_binutils
+  source $ROOTDIR/installation_scripts/setup_binutils
   if [ $? -ne 0 ]; then
     echo -e '\033[0;31m'"SCRIPT setup_binutils FAILED"'\033[0m'
     cd $ROOTDIR
@@ -271,7 +269,7 @@ if [ -z "${MINICONDA_INSTALLATION}" ]; then
 fi
 
 if [ -z "${MINICONDA_INSTALLATION}" ]; then
-  source ./installation_scripts/setup_hdf5
+  source $ROOTDIR/installation_scripts/setup_hdf5
   if [ $? -ne 0 ]; then
     echo -e '\033[0;31m'"SCRIPT setup_hdf5 FAILED"'\033[0m'
     cd $ROOTDIR
@@ -281,7 +279,7 @@ if [ -z "${MINICONDA_INSTALLATION}" ]; then
 fi
 
 if [ -z "${MINICONDA_INSTALLATION}" ]; then
-  source ./installation_scripts/setup_openblas
+  source $ROOTDIR/installation_scripts/setup_openblas
   if [ $? -ne 0 ]; then
     echo -e '\033[0;31m'"SCRIPT setup_openblas FAILED"'\033[0m'
     cd $ROOTDIR
@@ -289,7 +287,7 @@ if [ -z "${MINICONDA_INSTALLATION}" ]; then
   fi
 fi
 
-source ./installation_scripts/setup_pip_packages
+source $ROOTDIR/installation_scripts/setup_pip_packages
 if [ $? -ne 0 ]; then
   echo -e '\033[0;31m'"SCRIPT setup_pip_packages FAILED"'\033[0m'
   cd $ROOTDIR
@@ -297,7 +295,7 @@ if [ $? -ne 0 ]; then
   return 1
 fi
 
-source ./installation_scripts/setup_fortran_packages
+source $ROOTDIR/installation_scripts/setup_fortran_packages
 if [ $? -ne 0 ]; then
   echo -e '\033[0;31m'"SCRIPT setup_fortran_packages FAILED"'\033[0m'
   cd $ROOTDIR
@@ -305,7 +303,7 @@ if [ $? -ne 0 ]; then
   return 1
 fi
 
-source ./installation_scripts/setup_cpp_packages
+source $ROOTDIR/installation_scripts/setup_cpp_packages
 if [ $? -ne 0 ]; then
   echo -e '\033[0;31m'"SCRIPT setup_cpp_packages FAILED"'\033[0m'
   cd $ROOTDIR
@@ -313,9 +311,17 @@ if [ $? -ne 0 ]; then
   return 1
 fi
 
-source ./installation_scripts/setup_c_packages
+source $ROOTDIR/installation_scripts/setup_c_packages
 if [ $? -ne 0 ]; then
   echo -e '\033[0;31m'"SCRIPT setup_c_packages FAILED"'\033[0m'
+  cd $ROOTDIR
+  source stop_cocoa
+  return 1
+fi
+
+source $ROOTDIR/installation_scripts/setup_update_cobaya
+if [ $? -ne 0 ]; then
+  echo -e '\033[0;31m'"SCRIPT setup_update_cobaya FAILED"'\033[0m'
   cd $ROOTDIR
   source stop_cocoa
   return 1
