More bash script updates

diff --git a/Cocoa/compile_external_modules b/Cocoa/compile_external_modules
--- a/Cocoa/compile_external_modules
+++ b/Cocoa/compile_external_modules
@@ -1,7 +1,10 @@
-echo -e '\033[1;44m''COMPILING EXTERNAL MODULES''\033[0m'
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
+echo -e '\033[1;45m''COMPILING EXTERNAL MODULES''\033[0m'
 
 if [ -n "${ROOTDIR}" ]; then
-    source stop_cocoa
+  source stop_cocoa
 fi
 
 source start_cocoa
@@ -22,25 +25,25 @@ else
 fi
 
 if [ -z "${IGNORE_ALL_PIP_INSTALLATION}" ]; then
-    $PIP3 install --editable cobaya --prefix=$ROOTDIR/.local \
-        --find-links file:$ROOTDIR/../cocoa_installation_libraries/pip_cache \
-        --no-index > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
-    if [ $? -ne 0 ]; then
-      echo -e '\033[0;31m'"PIP COULD NOT RUN \e[3mPIP INSTALL COBAYA"'\033[0m'
-      cd $ROOTDIR
-      return 1
-    else
-      echo -e '\033[0;32m'"PIP RUN \e[3mPIP INSTALL COBAYA\e[0m\e\033[0;32m DONE"'\033[0m'
-    fi
+  $PIP3 install --editable cobaya --prefix=$ROOTDIR/.local \
+      --find-links file:$ROOTDIR/../cocoa_installation_libraries/pip_cache \
+      --no-index > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
+  if [ $? -ne 0 ]; then
+    echo -e '\033[0;31m'"PIP COULD NOT RUN \e[3mPIP INSTALL COBAYA"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  else
+    echo -e '\033[0;32m'"PIP RUN \e[3mPIP INSTALL COBAYA\e[0m\e\033[0;32m DONE"'\033[0m'
+  fi
 else
-    $PIP3 install --editable cobaya --prefix=$ROOTDIR/.local > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
-    if [ $? -ne 0 ]; then
-      echo -e '\033[0;31m'"PIP COULD NOT RUN \e[3mPIP INSTALL COBAYA"'\033[0m'
-      cd $ROOTDIR
-      return 1
-    else
-      echo -e '\033[0;32m'"PIP RUN \e[3mPIP INSTALL COBAYA\e[0m\e\033[0;32m DONE"'\033[0m'
-    fi
+  $PIP3 install --editable cobaya --prefix=$ROOTDIR/.local > ${OUTPUT_PIP_1} 2> ${OUTPUT_PIP_2}
+  if [ $? -ne 0 ]; then
+    echo -e '\033[0;31m'"PIP COULD NOT RUN \e[3mPIP INSTALL COBAYA"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  else
+    echo -e '\033[0;32m'"PIP RUN \e[3mPIP INSTALL COBAYA\e[0m\e\033[0;32m DONE"'\033[0m'
+  fi
 fi
 
 echo -e '\033[1;34m''\e[4mINSTALLING COBAYA (VIA PIP) DONE''\033[0m'
@@ -68,4 +71,7 @@ source $ROOTDIR/installation_scripts/compile_act
 # ----------------------------------------------------------------------------
 
 source stop_cocoa
-echo -e '\033[1;44m''\e[4mCOMPILING EXTERNAL MODULES DONE''\033[0m'
+echo -e '\033[1;45m''\e[4mCOMPILING EXTERNAL MODULES DONE''\033[0m'
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
