update

diff --git a/Cocoa/setup_cocoa_installation_packages b/Cocoa/setup_cocoa_installation_packages
--- a/Cocoa/setup_cocoa_installation_packages
+++ b/Cocoa/setup_cocoa_installation_packages
@@ -109,6 +109,13 @@ echo "FAILED setup_pip_packages SCRIPT" >&2
 return 1
 fi
 
+source ./installation_scripts/setup_fortran_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_fortran_packages SCRIPT" >&2
+return 1
+fi
+
 source ./installation_scripts/setup_cpp_packages
 if [ $? -ne 0 ] 
 then
@@ -120,13 +127,6 @@ source ./installation_scripts/setup_c_packages
 if [ $? -ne 0 ] 
 then
 echo "FAILED setup_c_packages SCRIPT" >&2
-return 1
-fi
-
-source ./installation_scripts/setup_fortran_packages
-if [ $? -ne 0 ] 
-then
-echo "FAILED setup_fortran_packages SCRIPT" >&2
 return 1
 fi
 
