update

diff --git a/Cocoa/setup_cocoa_installation_packages b/Cocoa/setup_cocoa_installation_packages
--- a/Cocoa/setup_cocoa_installation_packages
+++ b/Cocoa/setup_cocoa_installation_packages
@@ -8,13 +8,6 @@ fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 
-if [ -n "${SET_INSTALLATION_OPTIONS}" ]; then
-    source $SET_INSTALLATION_OPTIONS
-else
-    source set_installation_options
-fi
-
-
 function addvar () {
     local tmp="${!1}" ;
     tmp="${tmp//:${2}:/:}" ;
@@ -22,6 +15,10 @@ function addvar () {
     tmp="${tmp/%:${2}/}" ;
     export $1="${2}:${tmp}" ;
 }
+
+if [ -n "${OMP_NUM_THREADS}" ]; then
+    export OLD_OMP_NUM_THREADS=$OMP_NUM_THREADS
+fi
 
 if [ -n "${LD_LIBRARY_PATH}" ]; then
     export OLD_LD_LIBRARY_PATH=$LD_LIBRARY_PATH
@@ -33,6 +30,32 @@ fi
 
 if [ -n "${PATH}" ]; then
     export OLD_PATH=$PATH
+fi
+
+if [ -n "${C_INCLUDE_PATH}" ]; then
+    export OLD_C_INCLUDE_PATH=$C_INCLUDE_PATH
+fi
+
+if [ -n "${CPLUS_INCLUDE_PATH}" ]; then
+    export OLD_CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH
+fi
+
+if [ -n "${LDFLAGS}" ]; then
+    export OLD_LDFLAGS=$LDFLAGS
+fi
+
+if [ -n "${CPATH}" ]; then
+    export OLD_CPATH=$CPATH
+fi
+
+if [ -n "${NUMPY_HEADERS}" ]; then
+    export OLD_NUMPY_HEADERS=$NUMPY_HEADERS
+fi
+
+if [ -n "${SET_INSTALLATION_OPTIONS}" ]; then
+    source $SET_INSTALLATION_OPTIONS
+else
+    source set_installation_options
 fi
 
 # ----------------------------------------------------------------------------
@@ -55,9 +78,9 @@ cd ./Cocoa
 source $ROOTDIR/.local/bin/activate
 
 if [ -n "${GLOBAL_PACKAGES_LOCATION}" ]; then
-addvar PYTHONPATH $GLOBAL_PACKAGES_LOCATION/lib/python$PYTHON_VERSION/site-packages
+    addvar PYTHONPATH $GLOBAL_PACKAGES_LOCATION/lib/python$PYTHON_VERSION/site-packages
 
-addvar LD_LIBRARY_PATH $GLOBAL_PACKAGES_LOCATION/lib
+    addvar LD_LIBRARY_PATH $GLOBAL_PACKAGES_LOCATION/lib
 fi
 
 addvar LD_LIBRARY_PATH $ROOTDIR/.local/lib
@@ -67,6 +90,10 @@ addvar PYTHONPATH $ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages
 addvar PYTHONPATH $ROOTDIR/.local/lib
 
 addvar PATH $ROOTDIR/.local/bin
+
+export C_INCLUDE_PATH=$C_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
+
+export CPLUS_INCLUDE_PATH=$CPLUS_INCLUDE_PATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
 
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -109,6 +136,19 @@ echo "FAILED setup_pip_packages SCRIPT" >&2
 return 1
 fi
 
+export NUMPY_HEADERS=$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
+
+addvar LD_LIBRARY_PATH $ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/lib
+
+export CPATH=$CPATH:$ROOTDIR/.local/lib/python$PYTHON_VERSION/site-packages/numpy/core/include
+
+source ./installation_scripts/setup_fortran_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_fortran_packages SCRIPT" >&2
+return 1
+fi
+
 source ./installation_scripts/setup_cpp_packages
 if [ $? -ne 0 ] 
 then
@@ -123,22 +163,6 @@ echo "FAILED setup_c_packages SCRIPT" >&2
 return 1
 fi
 
-source ./installation_scripts/setup_fortran_packages
-if [ $? -ne 0 ] 
-then
-echo "FAILED setup_fortran_packages SCRIPT" >&2
-return 1
-fi
-
-
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-# ------------------------ CLONE EXTERNAL PROJECTS ---------------------------
-# ----------------------------------------------------------------------------
-# ----------------------------------------------------------------------------
-
-source $ROOTDIR/projects/clone_all.sh
-
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -146,4 +170,3 @@ source $ROOTDIR/projects/clone_all.sh
 # ----------------------------------------------------------------------------
 
 source stop_cocoa
-
