v3.0

diff --git a/Cocoa/installation_scripts/clean_required b/Cocoa/installation_scripts/clean_required
--- a/Cocoa/installation_scripts/clean_required
+++ b/Cocoa/installation_scripts/clean_required
@@ -1,6 +1,6 @@
 if [ -z "${ROOTDIR}" ]; then
-  echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
-  return 1
+    echo 'ERROR ENV VARIABLE ROOTDIR IS NOT DEFINED' >&2
+    return 1
 fi
 
 cd $ROOTDIR/../cocoa_installation_libraries
diff --git a/Cocoa/installation_scripts/compile_cambede b/Cocoa/installation_scripts/compile_cambede
--- a/Cocoa/installation_scripts/compile_cambede
+++ b/Cocoa/installation_scripts/compile_cambede
@@ -29,44 +29,45 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_CAMB_COMPILATION}" ]; then
-    echo 'COMPILING CAMB EDE'
+  echo 'COMPILING CAMB EDE'
 
-    cd $ROOTDIR/external_modules/code/CAMB-EDE/
+  cd $ROOTDIR/external_modules/code/CAMB-EDE/
 
-    rm -rf ./build/
+  rm -rf ./build/
 
-    rm -rf ./camb/__pycache__/
+  rm -rf ./camb/__pycache__/
 
-    rm -f ./camb/camblib.so
+  rm -f ./camb/camblib.so
 
-    rm -rf ./forutils/Releaselib/
+  rm -rf ./forutils/Releaselib/
 
-    if [ -z "${DEBUG_CAMB_OUTPUT}" ]; then
-      export OUTPUT_CAMB_1="/dev/null"
-      export OUTPUT_CAMB_2="/dev/null"
-    else
-      export OUTPUT_CAMB_1="/dev/tty"
-      export OUTPUT_CAMB_2="/dev/tty"
-    fi
+  if [ -z "${DEBUG_CAMB_OUTPUT}" ]; then
+    export OUTPUT_CAMB_1="/dev/null"
+    export OUTPUT_CAMB_2="/dev/null"
+  else
+    export OUTPUT_CAMB_1="/dev/tty"
+    export OUTPUT_CAMB_2="/dev/tty"
+  fi
 
-    $PYTHON3 setup.py clean > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
-    if [ $? -ne 0 ]; then
-      echo "CAMB EDE COULD NOT RUN PYTHON3 SETUP.PY CLEAN"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CAMB EDE PYTHON3 SETUP.PY CLEAN DONE"
-    fi
-
-    COMPILER=$FORTRAN_COMPILER F90C=$FORTRAN_COMPILER $PYTHON3 setup.py build \
-      > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
-    if [ $? -ne 0 ]; then
-      echo "CAMB COULD NOT RUN PYTHON3 SETUP.PY BUILD"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CAMB EDE PYTHON3 SETUP.PY BUILD DONE"
-    fi
-
+  $PYTHON3 setup.py clean > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
+  if [ $? -ne 0 ]; then
+    echo "CAMB EDE COULD NOT RUN PYTHON3 SETUP.PY CLEAN"
     cd $ROOTDIR
+    return 1
+  else
+    echo "CAMB EDE PYTHON3 SETUP.PY CLEAN DONE"
+  fi
+
+  COMPILER=$FORTRAN_COMPILER F90C=$FORTRAN_COMPILER $PYTHON3 setup.py build \
+    > ${OUTPUT_CAMB_1} 2> ${OUTPUT_CAMB_2}
+  if [ $? -ne 0 ]; then
+    echo "CAMB COULD NOT RUN PYTHON3 SETUP.PY BUILD"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "CAMB EDE PYTHON3 SETUP.PY BUILD DONE"
+  fi
+
+  cd $ROOTDIR
+  echo 'COMPILING CAMB EDE DONE'
 fi
diff --git a/Cocoa/installation_scripts/compile_class b/Cocoa/installation_scripts/compile_class
--- a/Cocoa/installation_scripts/compile_class
+++ b/Cocoa/installation_scripts/compile_class
@@ -29,59 +29,60 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_CLASS_COMPILATION}" ]; then
-    echo 'COMPILING CLASS'
+  echo 'COMPILING CLASS'
 
-    cd $ROOTDIR/external_modules/code/class_public/
+  cd $ROOTDIR/external_modules/code/class_public/
 
-    if [ -z "${DEBUG_CLASS_OUTPUT}" ]; then
-      export OUTPUT_CLASS_1="/dev/null"
-      export OUTPUT_CLASS_2="/dev/null"
-    else
-      export OUTPUT_CLASS_1="/dev/tty"
-      export OUTPUT_CLASS_2="/dev/tty"
-    fi
+  if [ -z "${DEBUG_CLASS_OUTPUT}" ]; then
+    export OUTPUT_CLASS_1="/dev/null"
+    export OUTPUT_CLASS_2="/dev/null"
+  else
+    export OUTPUT_CLASS_1="/dev/tty"
+    export OUTPUT_CLASS_2="/dev/tty"
+  fi
 
-    make clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
-    if [ $? -ne 0 ]; then
-      echo "CLASS COULD NOT RUN MAKE CLEAN"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CLASS MAKE CLEAN RUN DONE"
-    fi
-
-    rm -f class
-
-    CC=$C_COMPILER PYTHON=$PYTHON3 make -j $MAKE_NUM_THREADS > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
-    if [ $? -ne 0 ]; then
-      echo "CLASS COULD NOT RUN MAKE"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CLASS MAKE RUN DONE"
-    fi
-
-    cd ./python
-
-    $PYTHON3 setup.py clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
-    if [ $? -ne 0 ]; then
-      echo "CLASS COULD NOT PYTHON3 SETUP.PY CLEAN"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CLASS PYTHON3 SETUP.PY CLEAN DONE"
-    fi
-
-    rm -rf ./build/
-
-    CC=$C_COMPILER $PYTHON3 setup.py build > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
-    if [ $? -ne 0 ]; then
-      echo "CLASS COULD NOT PYTHON3 SETUP.PY BUILD"
-      cd $ROOTDIR
-      return 1
-    else
-      echo "CLASS PYTHON3 SETUP.PY BUILD DONE"
-    fi
-
+  make clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  if [ $? -ne 0 ]; then
+    echo "CLASS COULD NOT RUN MAKE CLEAN"
     cd $ROOTDIR
+    return 1
+  else
+    echo "CLASS MAKE CLEAN RUN DONE"
+  fi
+
+  rm -f class
+
+  CC=$C_COMPILER PYTHON=$PYTHON3 make -j $MAKE_NUM_THREADS > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  if [ $? -ne 0 ]; then
+    echo "CLASS COULD NOT RUN MAKE"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "CLASS MAKE RUN DONE"
+  fi
+
+  cd ./python
+
+  $PYTHON3 setup.py clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  if [ $? -ne 0 ]; then
+    echo "CLASS COULD NOT PYTHON3 SETUP.PY CLEAN"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "CLASS PYTHON3 SETUP.PY CLEAN DONE"
+  fi
+
+  rm -rf ./build/
+
+  CC=$C_COMPILER $PYTHON3 setup.py build > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  if [ $? -ne 0 ]; then
+    echo "CLASS COULD NOT PYTHON3 SETUP.PY BUILD"
+    cd $ROOTDIR
+    return 1
+  else
+    echo "CLASS PYTHON3 SETUP.PY BUILD DONE"
+  fi
+
+  cd $ROOTDIR
+  echo 'COMPILING CLASS DONE'
 fi
