More bash script updates

diff --git a/Cocoa/installation_scripts/clean_act b/Cocoa/installation_scripts/clean_act
--- a/Cocoa/installation_scripts/clean_act
+++ b/Cocoa/installation_scripts/clean_act
@@ -12,6 +12,13 @@ fi
 # ------------------------------- REMOVE ACT ---------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
+if [ -z "${DEBUG_ACT_OUTPUT}" ]; then
+export OUTPUT_ACT_1="/dev/null"
+export OUTPUT_ACT_2="/dev/null"
+else
+export OUTPUT_ACT_1="/dev/tty"
+export OUTPUT_ACT_2="/dev/tty"
+fi
 
 cd $ROOTDIR/external_modules/code/pyactlike/
 
@@ -19,6 +26,11 @@ rm -rf ./build/
 
 rm -rf ./pyactlike.egg-info/
 
-$PYTHON3 setup.py clean
+$PYTHON3 setup.py clean > ${OUTPUT_ACT_1} 2> ${OUTPUT_ACT_2}
+if [ $? -ne 0 ]; then
+echo -e '\033[0;31m'"ACT COULD NOT RUN \e[3mPYTHON3 SETUP.PY CLEAN"'\033[0m'
+else
+echo -e '\033[0;32m'"ACT RUN \e[3mPYTHON3 SETUP.PY CLEAN\e[0m\e\033[0;32m DONE"'\033[0m'
+fi
 
 cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/setup_binutils b/Cocoa/installation_scripts/setup_binutils
--- a/Cocoa/installation_scripts/setup_binutils
+++ b/Cocoa/installation_scripts/setup_binutils
@@ -23,127 +23,104 @@ if [ -z "${MAKE_NUM_THREADS}" ]; then
     return 1
 fi
 
+if [ -z "${DEBUG_DISTUTILS_PACKAGE}" ]; then
+  export OUTPUT_DISTUTILS_PACKAGES_1="/dev/null"
+  export OUTPUT_DISTUTILS_PACKAGES_2="/dev/null"
+  export DISTUTILS_MAKE_NUM_THREADS="${MAKE_NUM_THREADS}"
+else
+  export OUTPUT_DISTUTILS_PACKAGES_1="/dev/tty"
+  export OUTPUT_DISTUTILS_PACKAGES_2="/dev/tty"
+  export DISTUTILS_MAKE_NUM_THREADS=1
+fi
+
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
+# ----------------------------- TEXINFO LIBRARY  -----------------------------
+# ----------------------------------------------------------------------------
+# ----------------------------------------------------------------------------
+if [ -z "${IGNORE_DISTUTILS_INSTALLATION}" ]; then
+  echo -e '\033[1;34m''INSTALLING TEXINFO LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
+
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+  cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_TEXINFO_DIR
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+
+  FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local \
+    --disable-perl-xs > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"TEXINFO RUN \e[3mCONFIGURE\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"TEXINFO COULD NOT RUN \e[3mCONFIGURE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make -j $DISTUTILS_MAKE_NUM_THREADS all > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"TEXINFO RUN \e[3mMAKE\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"TEXINFO COULD NOT RUN \e[3mMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"TEXINFO RUN \e[3mMAKE INSTALL\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"TEXINFO COULD NOT RUN \e[3mMAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  cd $ROOTDIR/
+  echo -e '\033[1;34m''\e[4mINSTALLING TEXINFO LIBRARY DONE''\033[0m'
+fi
 
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------- DISTUTILS LIBRARY  ---------------------------
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
-
 if [ -z "${IGNORE_DISTUTILS_INSTALLATION}" ]; then
-  echo 'INSTALLING TEXINFO - THAT WILL TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING BINUTILS LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
-  cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_TEXINFO_DIR
-
-  if [ -z "${DEBUG_DISTUTILS_PACKAGE}" ]; then
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local \
-      --disable-perl-xs > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "TEXINFO CONFIGURE RUN DONE"
-    else
-      echo "TEXINFO COULD NOT RUN CONFIGURE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "TEXINFO MAKE RUN DONE"
-    else
-      echo "TEXINFO COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "TEXINFO MAKE INSTALL RUN DONE"
-    else
-      echo "TEXINFO COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-  else
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local \
-      --disable-perl-xs
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
-
-    make
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
-
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
-
-    make TEXMF=$ROOTDIR/.local install-tex
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
-  fi
-  echo 'INSTALLING TEXINFO - DONE'
-  # ----------------------------------------------------------------------------------------
-  # ----------------------------------------------------------------------------------------
-  # ----------------------------------------------------------------------------------------
-  echo 'INSTALLING BINUTILS - THAT WILL TAKE A WHILE'
-
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_BINUTILS_DIR
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
 
-  if [ -z "${DEBUG_DISTUTILS_PACKAGE}" ]; then
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "BINUTILS CONFIGURE RUN DONE"
-    else
-      echo "BINUTILS COULD NOT RUN CONFIGURE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "BINUTILS MAKE RUN DONE"
-    else
-      echo "BINUTILS COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "BINUTILS MAKE INSTALL RUN DONE"
-    else
-      echo "BINUTILS COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+  FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure \
+    --prefix=$ROOTDIR/.local > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"BINUTILS RUN \e[3mCONFIGURE\e[0m\e\033[0;32m DONE"'\033[0m'
   else
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo -e '\033[0;31m'"BINUTILS COULD NOT RUN \e[3mCONFIGURE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $DISTUTILS_MAKE_NUM_THREADS > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"BINUTILS RUN \e[3mMAKE\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"BINUTILS COULD NOT RUN \e[3mMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make install > ${OUTPUT_DISTUTILS_PACKAGES_1} 2> ${OUTPUT_DISTUTILS_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"BINUTILS RUN \e[3mMAKE INSTALL\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"BINUTILS COULD NOT RUN \e[3mMAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR/
-  echo 'INSTALLING BINUTILS - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING BINUTILS LIBRARY DONE''\033[0m'
 fi
diff --git a/Cocoa/installation_scripts/setup_cmake b/Cocoa/installation_scripts/setup_cmake
--- a/Cocoa/installation_scripts/setup_cmake
+++ b/Cocoa/installation_scripts/setup_cmake
@@ -25,57 +25,52 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_CMAKE_INSTALLATION}" ]; then
-  echo 'INSTALLING CMAKE - THAT WILL TAKE A WHILE'
-
-  cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_CMAKE_DIR
+  echo -e '\033[1;34m''INSTALLING CMAKE LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
   if [ -z "${DEBUG_CMAKE_PACKAGE}" ]; then
-    env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CMAKE BOOTSTRAP RUN DONE"
-    else
-      echo "CMAKE COULD NOT RUN BOOTSTRAP" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CMAKE MAKE RUN DONE"
-    else
-      echo "CMAKE COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CMAKE MAKE INSTALL RUN DONE"
-    else
-      echo "CMAKE COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+    export OUTPUT_CMAKE_PACKAGES_1="/dev/null"
+    export OUTPUT_CMAKE_PACKAGES_2="/dev/null"
+    export CMAKE_MAKE_NUM_THREADS="${MAKE_NUM_THREADS}"
   else
-    env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    export OUTPUT_CMAKE_PACKAGES_1="/dev/tty"
+    export OUTPUT_CMAKE_PACKAGES_2="/dev/tty"
+    export CMAKE_MAKE_NUM_THREADS=1
+  fi
 
-    make
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+  cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_CMAKE_DIR
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+
+  env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap \
+    --prefix=$ROOTDIR/.local > ${OUTPUT_CMAKE_PACKAGES_1} 2> ${OUTPUT_CMAKE_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"CMAKE RUN \e[3mBOOTSTRAP\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"CMAKE COULD NOT RUN \e[3mBOOTSTRAP"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make -j $CMAKE_MAKE_NUM_THREADS > ${OUTPUT_CMAKE_PACKAGES_1} 2> ${OUTPUT_CMAKE_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"CMAKE RUN \e[3mMAKE\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"CMAKE COULD NOT RUN \e[3mMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_CMAKE_PACKAGES_1} 2> ${OUTPUT_CMAKE_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"CMAKE RUN \e[3mMAKE INSTALL\e[0m\e\033[0;32m DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"CMAKE COULD NOT RUN \e[3mMAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
-  echo 'INSTALLING CMAKE - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING CMAKE LIBRARY DONE''\033[0m'
 fi
