Changes to bash setup and compile files + classy

diff --git a/Cocoa/installation_scripts/compile_class b/Cocoa/installation_scripts/compile_class
--- a/Cocoa/installation_scripts/compile_class
+++ b/Cocoa/installation_scripts/compile_class
@@ -29,14 +29,14 @@ fi
 # ----------------------------------------------------------------------------
 
 if [ -z "${IGNORE_CLASS_COMPILATION}" ]; then
-  echo 'COMPILING CLASS'
+  echo -e '\033[1;34m''COMPILING CLASS''\033[0m'
 
+  # ---------------------------------------------------------------------------
+  # ---------------------------------------------------------------------------
   cd $ROOTDIR/external_modules/code/class_public/
-
-  #Workaround Cocoa .gitignore entry on /include
-  rm -rf $ROOTDIR/external_modules/code/class_public/include
-  cp -r $ROOTDIR/external_modules/code/class_public/include2 $ROOTDIR/external_modules/code/class_public/include
-
+  # ---------------------------------------------------------------------------
+  # ---------------------------------------------------------------------------
+  
   if [ -z "${DEBUG_CLASS_OUTPUT}" ]; then
     export OUTPUT_CLASS_1="/dev/null"
     export OUTPUT_CLASS_2="/dev/null"
@@ -45,48 +45,59 @@ if [ -z "${IGNORE_CLASS_COMPILATION}" ]; then
     export OUTPUT_CLASS_2="/dev/tty"
   fi
 
+  # ---------------------------------------------------------------------------
+  # ---------------------------------------------------------------------------
+  #Workaround Cocoa .gitignore entry on /include
+  rm -rf ./include > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  cp -r  ./include2 ./include > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+
   make clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
   if [ $? -ne 0 ]; then
-    echo "CLASS COULD NOT RUN MAKE CLEAN"
+    echo -e '\033[0;31m'"CLASS COULD NOT RUN \e[3mMAKE CLEAN\e[0m"'\033[0m'
     cd $ROOTDIR
     return 1
   else
-    echo "CLASS MAKE CLEAN RUN DONE"
+    echo -e '\033[0;32m'"CLASS RUN \e[3mMAKE CLEAN RUN\e[0m\e\033[0;32m DONE"'\033[0m'
   fi
 
   rm -f class
-
-  CC=$C_COMPILER PYTHON=$PYTHON3 make -j $MAKE_NUM_THREADS > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
-  if [ $? -ne 0 ]; then
-    echo "CLASS COULD NOT RUN MAKE"
-    cd $ROOTDIR
-    return 1
-  else
-    echo "CLASS MAKE RUN DONE"
-  fi
 
   cd ./python
 
   $PYTHON3 setup.py clean > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
   if [ $? -ne 0 ]; then
-    echo "CLASS COULD NOT PYTHON3 SETUP.PY CLEAN"
+    echo -e '\033[0;31m'"CLASS COULD NOT RUN \e[3mPYTHON3 SETUP.PY CLEAN\e[0m"'\033[0m'
     cd $ROOTDIR
     return 1
   else
-    echo "CLASS PYTHON3 SETUP.PY CLEAN DONE"
+    echo -e '\033[0;32m'"CLASS RUN \e[3mPYTHON3 SETUP.PY CLEAN\e[0m\e\033[0;32m DONE"'\033[0m'
   fi
 
   rm -rf ./build/
- 
-  CC=$C_COMPILER $PYTHON3 setup.py build > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  cd ../
+  # ---------------------------------------------------------------------------
+  # ---------------------------------------------------------------------------
+
+  CC=$C_COMPILER PYTHON=$PYTHON3 make all > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
   if [ $? -ne 0 ]; then
-    echo "CLASS COULD NOT PYTHON3 SETUP.PY BUILD"
+    echo -e '\033[0;31m'"CLASS COULD NOT RUN \e[3mMAKE ALL\e[0m"'\033[0m'
     cd $ROOTDIR
     return 1
   else
-    echo "CLASS PYTHON3 SETUP.PY BUILD DONE"
+    echo -e '\033[0;32m'"CLASS RUN \e[3mMAKE ALL\e[0m\e\033[0;32m DONE"'\033[0m'
+  fi
+   
+  cd ./python
+
+  CC=$C_COMPILER $PYTHON3 setup.py build > ${OUTPUT_CLASS_1} 2> ${OUTPUT_CLASS_2}
+  if [ $? -ne 0 ]; then
+    echo -e '\033[0;31m'"CLASS COULD NOT RUN \e[3mPYTHON3 SETUP.PY BUILD\e[0m"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  else
+    echo -e '\033[0;32m'"CLASS RUN \e[3mPYTHON3 SETUP.PY BUILD\e[0m\e\033[0;32m DONE"'\033[0m'
   fi
 
   cd $ROOTDIR
-  echo 'COMPILING CLASS DONE'
+  echo -e '\033[1;34m''\e[4mCOMPILING CLASS DONE''\033[0m'
 fi
diff --git a/Cocoa/installation_scripts/setup_c_packages b/Cocoa/installation_scripts/setup_c_packages
--- a/Cocoa/installation_scripts/setup_c_packages
+++ b/Cocoa/installation_scripts/setup_c_packages
@@ -31,62 +31,48 @@ fi
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
 
+if [ -z "${DEBUG_C_PACKAGES}" ]; then
+  export OUTPUT_CPACKAGES_1="/dev/null"
+  export OUTPUT_CPACKAGES_2="/dev/null"
+else
+  export OUTPUT_CPACKAGES_1="/dev/tty"
+  export OUTPUT_CPACKAGES_2="/dev/tty"
+fi
+
 # --------------------------------------------------------------------------------------
 # ---------------------------------------- FFTW ----------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
-  echo 'INSTALLING C FFTW LIBRARY - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING FFTW C LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
-  
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_FFTW_DIR
   
-  if [ -z "${DEBUG_C_PACKAGES}" ]; then
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
-    --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "FFTW CONFIGURE RUN DONE"
-    else
-      echo "FFTW COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "FFTW MAKE RUN DONE"
-    else
-      echo "FFTW COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "FFTW MAKE INSTALL RUN DONE"
-    else
-      echo "FFTW COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+  FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
+  --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "FFTW RUN CONFIGURE DONE"
   else
-    FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp \
-    --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo "FFTW COULD NOT RUN CONFIGURE"
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $MAKE_NUM_THREADS all > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "FFTW RUN MAKE DONE"
+  else
+    echo "FFTW COULD NOT RUN MAKE"
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make install > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "FFTW MAKE INSTALL RUN DONE"
+  else
+    echo "FFTW COULD NOT RUN MAKE INSTALL"
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
@@ -97,7 +83,7 @@ fi
 # --------------------------------------- CFITSIO --------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
-  echo 'INSTALLING C CFITSIO LIBRARY - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING CFITSIO C LIBRARY - \e[4mIT MIGHT TAKE A WHILE''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_CFITSIO_DIR
 
@@ -106,55 +92,34 @@ if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
   mkdir ./CFITSIOBUILD
   cd ./CFITSIOBUILD
 
-  if [ -z "${DEBUG_C_PACKAGES}" ]; then
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+  $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
     -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR ..  > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CFITSIO CMAKE RUN DONE"
-    else
-      echo "CFITSIO COULD NOT RUN CMAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CFITSIO MAKE RUN DONE"
-    else
-      echo "CFITSIO COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "CFITSIO MAKE INSTALL RUN DONE"
-    else
-      echo "CFITSIO COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER \
+    --log-level=ERROR .. > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "CFITSIO RUN CMAKE DONE"
   else
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
-    -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER ..
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo "CFITSIO COULD NOT RUN CMAKE"
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $MAKE_NUM_THREADS all > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "CFITSIO RUN MAKE DONE"
+  else
+    echo "CFITSIO COULD NOT RUN MAKE"
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make install > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "CFITSIO RUN MAKE INSTALL DONE"
+  else
+    echo "CFITSIO COULD NOT RUN MAKE INSTALL"
+    cd $ROOTDIR
+    return 1
   fi
 
   cd ../
@@ -168,58 +133,36 @@ fi
 # ----------------------------------------- GSL ----------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
-  echo 'INSTALLING C GSL LIBRARY - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING GSL C LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_GSL_DIR
 
-  if [ -z "${DEBUG_C_PACKAGES}" ]; then
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
-    --enable-static=yes > /dev/null 2> /dev/null
-    if [ $? -eq 0 ] 
-    then
-      echo "GSL CONFIGURE RUN DONE"
-    else
-      echo "GSL COULD NOT RUN CONFIGURE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "GSL MAKE RUN DONE"
-    else
-      echo "GSL COULD NOT RUN MAKE - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "MAKE INSTALL GSL OK"
-    else
-      echo "GSL COULD NOT RUN MAKE INSTALL - CHECK SETUP_C_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+  CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
+    --enable-static=yes > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "GSL RUN CONFIGURE DONE"
   else
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes \
-    --enable-static=yes
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo "GSL COULD NOT RUN CONFIGURE"
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $MAKE_NUM_THREADS all > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "GSL RUN MAKE DONE"
+  else
+    echo "GSL COULD NOT RUN MAKE"
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_CPACKAGES_1} 2> ${OUTPUT_CPACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo "GSL RUN MAKE INSTALL DONE"
+  else
+    echo "GSL COULD NOT RUN MAKE INSTALL"
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
diff --git a/Cocoa/installation_scripts/setup_cpp_packages b/Cocoa/installation_scripts/setup_cpp_packages
--- a/Cocoa/installation_scripts/setup_cpp_packages
+++ b/Cocoa/installation_scripts/setup_cpp_packages
@@ -35,7 +35,7 @@ fi
 # --------------------------------------- SPDLOG ---------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
-  echo 'INSTALLING CPP SPDLOG LIBRARY - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING SPDLOG C++ LIBRARY - \e[4mIT MAY TAKE A WHILE''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_SPDLOG_DIR
 
@@ -45,7 +45,7 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
     $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
     -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
     if [ $? -eq 0 ];then
-      echo "SPDLOG CMAKE RUN DONE"
+      echo "SPDLOG RUN CMAKE DONE"
     else
       echo "SPDLOG COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
       cd $ROOTDIR
@@ -54,18 +54,18 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "SPDLOG MAKE RUN DONE"
+      echo "SPDLOG RUN MAKE DONE"
     else
-      echo "SPDLOG COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "SPDLOG COULD NOT RUN MAKE" >&2
       cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null
     if [ $? -eq 0 ]; then
-      echo "SPDLOG MAKE INSTALL RUN DONE"
+      echo "SPDLOG RUN MAKE INSTALL DONE"
     else
-      echo "SPDLOG COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "SPDLOG COULD NOT RUN MAKE INSTALL" >&2
       cd $ROOTDIR
       return 1
     fi
@@ -90,14 +90,14 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
   fi
 
   cd $ROOTDIR
-  echo 'INSTALLING CPP SPDLOG LIBRARY - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING SPDLOG C++ LIBRARY DONE''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
 # ------------------------------------- ARMADILLO --------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
-  echo 'INSTALLING CPP ARMADILLO LIBRARY - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING ARMADILLO C++ LIBRARY - \e[4mIT MAY TAKE A WHILE''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_ARMADILLO_DIR
 
@@ -109,9 +109,9 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
     -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
     -DBLAS_FOUND=NO --log-level=ERROR . > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "ARMADILLO CMAKE RUN DONE"
+      echo "ARMADILLO RUN CMAKE DONE"
     else
-      echo "ARMADILLO COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "ARMADILLO COULD NOT RUN CMAKE"
       cd $ROOTDIR
       return 1
     fi
@@ -119,18 +119,18 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
     make clean
     make -j $MAKE_NUM_THREADS all -Wno-dev > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "ARMADILLO MAKE RUN DONE"
+      echo "ARMADILLO RUN MAKE DONE"
     else
-      echo "ARMADILLO COULD NOT RUN MAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "ARMADILLO COULD NOT RUN MAKE"
       cd $ROOTDIR
       return 1
     fi
 
     make install > /dev/null
     if [ $? -eq 0 ]; then
-      echo "ARMADILLO MAKE INSTALL RUN DONE"
+      echo "ARMADILLO RUN MAKE INSTALL DONE"
     else
-      echo "ARMADILLO COULD NOT RUN MAKE INSTALL - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "ARMADILLO COULD NOT RUN MAKE INSTALL"
       cd $ROOTDIR
       return 1
     fi
@@ -158,14 +158,14 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
   fi
 
   cd $ROOTDIR
-  echo 'INSTALLING CPP ARMADILLO LIBRARY - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING ARMADILLO C++ LIBRARY DONE''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
 # --------------------------- CARMA (ARMADILLO <-> PYBIND11) ---------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_CARMA_INSTALLATION}" ]; then
-  echo 'INSTALLING CARMA -  THE PYTHON <-> ARMADILLO CONVERSION - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING CARMA C++ LIBRARY''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_CARMA_DIR
 
@@ -178,32 +178,32 @@ if [ -z "${IGNORE_CPP_CARMA_INSTALLATION}" ]; then
   cp -r ./carma_bits $ROOTDIR/.local/include/
 
   cd $ROOTDIR
-  echo 'INSTALLING CARMA -  THE PYTHON <-> ARMADILLO CONVERSION - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING CARMA C++ LIBRARY DONE''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
 # ---------------------------------------- BOOST ---------------------------------------
 # --------------------------------------------------------------------------------------
 if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
-  echo 'INSTALLING CPP BOOST LIBRARY - THIS WILL TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING BOOST C++ LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_BOOST_DIR
 
   if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
     ./bootstrap.sh --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "BOOST BOOTSTRAP RUN DONE"
+      echo "BOOST RUN BOOTSTRAP DONE"
     else
-      echo "BOOST COULD NOT RUN BOOTSTRAP - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "BOOST COULD NOT RUN BOOTSTRAP" >&2
       return 1
     fi
 
     ./b2 --with=regex install --without-python --without-thread \
     --without-timer --without-mpi --without-atomic > /dev/null 2> /dev/null
     if [ $? -eq 0 ]; then
-      echo "BOOST B2 RUN DONE"
+      echo "BOOST RUN B2 DONE"
     else
-      echo "BOOST COULD NOT RUN B2 - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
+      echo "BOOST COULD NOT RUN B2"
       return 1
     fi
   else
@@ -222,7 +222,7 @@ if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
   fi
   
   cd $ROOTDIR
-  echo 'INSTALLING CPP BOOST LIBRARY - DONE'
+  echo -e '\033[1;34m''\e[4mINSTALLING BOSST C++ LIBRARY DONE''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
