update

diff --git a/Cocoa/installation_scripts/setup_c_packages b/Cocoa/installation_scripts/setup_c_packages
--- a/Cocoa/installation_scripts/setup_c_packages
+++ b/Cocoa/installation_scripts/setup_c_packages
@@ -36,8 +36,22 @@ if [ -z "${IGNORE_C_FFTW_INSTALLATION}" ]; then
     FC=$FORTRAN_COMPILER CC=$C_COMPILER ./configure --enable-openmp --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
 
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE FFTW OK"
+    else
+      echo "FFTW COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL FFTW OK"
+    else
+      echo "FFTW COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
@@ -51,8 +65,22 @@ if [ -z "${IGNORE_C_CFITSIO_INSTALLATION}" ]; then
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR .  > /dev/null 2> /dev/null
 
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE CFITSIO OK"
+    else
+      echo "CFITSIO COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL CFITSIO OK"
+    else
+      echo "CFITSIO COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
@@ -64,8 +92,22 @@ if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
     CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local --enable-shared=yes --enable-static=yes > /dev/null 2> /dev/null
 
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE CFITSIO OK"
+    else
+      echo "CFITSIO COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL GSL OK"
+    else
+      echo "GSL COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
diff --git a/Cocoa/installation_scripts/setup_cmake b/Cocoa/installation_scripts/setup_cmake
--- a/Cocoa/installation_scripts/setup_cmake
+++ b/Cocoa/installation_scripts/setup_cmake
@@ -26,10 +26,31 @@ if [ -z "${IGNORE_CMAKE_INSTALLATION}" ]; then
     cd $ROOTDIR/../cocoa_installation_libraries/cmake-3.17.1
 
     env CC=$C_COMPILER CXX=$CPP_COMPILER ./bootstrap --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "BOOTSTRAP CMAKE OK"
+    else
+      echo "CMAKE COULD NOT BOOTSTRAP" >&2
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE CMAKE OK"
+    else
+      echo "CMAKE COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL CMAKE OK"
+    else
+      echo "CMAKE COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
diff --git a/Cocoa/installation_scripts/setup_cpp_packages b/Cocoa/installation_scripts/setup_cpp_packages
--- a/Cocoa/installation_scripts/setup_cpp_packages
+++ b/Cocoa/installation_scripts/setup_cpp_packages
@@ -36,10 +36,31 @@ if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
     rm -f CMakeCache.txt
 
     $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "CMAKE SPDLOG OK"
+    else
+      echo "SPDLOG COULD NOT CMAKE" >&2
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE SPDLOG OK"
+    else
+      echo "SPDLOG COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL SPDLOG OK"
+    else
+      echo "SPDLOG COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
@@ -51,10 +72,31 @@ if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
     rm -f CMakeCache.txt
 
     $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_FC_COMPILER=FORTRAN_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "CMAKE ARMA OK"
+    else
+      echo "ARMA COULD NOT CMAKE" >&2
+      return 1
+    fi
 
     make -j $MAKE_NUM_THREADS all -Wno-dev > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE ARMA OK"
+    else
+      echo "ARMA COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install > /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL ARMA OK"
+    else
+      echo "ARMA COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
 
     cd $ROOTDIR
 fi
@@ -79,8 +121,22 @@ if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
     cd $ROOTDIR/../cocoa_installation_libraries/boost_1_72_0/
 
     ./bootstrap.sh --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "bootstrap BOOST OK"
+    else
+      echo "BOOST COULD NOT bootstrap" >&2
+      return 1
+    fi
 
     ./b2 --with=regex install > /dev/null 2> /dev/null
-
+    if [ $? -eq 0 ] 
+    then
+      echo "B2 BOOST OK"
+    else
+      echo "BOOST COULD NOT B2" >&2
+      return 1
+    fi
+    
     cd $ROOTDIR
 fi
diff --git a/Cocoa/installation_scripts/setup_fortran_packages b/Cocoa/installation_scripts/setup_fortran_packages
--- a/Cocoa/installation_scripts/setup_fortran_packages
+++ b/Cocoa/installation_scripts/setup_fortran_packages
@@ -1,26 +1,26 @@
 if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ROOTDIR not defined'
-    return
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
     echo 'ERROR CXX_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
     echo 'ERROR C_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${FORTRAN_COMPILER}" ]; then
     echo 'ERROR C_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${CMAKE}" ]; then
     echo 'ERROR CMAKE not defined'
-    return
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
     echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    return 1
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -39,11 +39,33 @@ if [ -z "${IGNORE_FORTRAN_INSTALLATION}" ]; then
 
         cd ./lapack-build
 
-        $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCMAKE_FC_COMPILER=$FORTRAN_COMPILER --log-level=ERROR ../lapack-3.9.0/ > /dev/null 2> /dev/null
+        $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../lapack-3.9.0/ > /dev/null 2> /dev/null
+        
+        if [ $? -eq 0 ] 
+        then
+          echo "CMAKE LAPACK OK"
+        else
+          echo "LAPACK COULD NOT CMAKE" >&2
+          return 1
+        fi
 
         make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
+        if [ $? -eq 0 ] 
+        then
+          echo "MAKE LAPACK OK"
+        else
+          echo "LAPACK COULD NOT MAKE" >&2
+          return 1
+        fi
 
         make install > /dev/null 2> /dev/null
+        if [ $? -eq 0 ] 
+        then
+          echo "MAKE INSTALL LAPACK OK"
+        else
+          echo "LAPACK COULD NOT MAKE INSTALL" >&2
+          return 1
+        fi
 
         cd $ROOTDIR
     fi
diff --git a/Cocoa/installation_scripts/setup_openblas b/Cocoa/installation_scripts/setup_openblas
--- a/Cocoa/installation_scripts/setup_openblas
+++ b/Cocoa/installation_scripts/setup_openblas
@@ -1,18 +1,18 @@
 if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ROOTDIR not defined'
-    return
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
     echo 'ERROR CXX_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
     echo 'ERROR C_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
     echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    return 1
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -26,9 +26,24 @@ if [ -z "${IGNORE_OPENBLAS_INSTALLATION}" ]; then
     cd $ROOTDIR/../cocoa_installation_libraries/OpenBLAS
 
     export MAKE_NB_JOBS=$MAKE_NUM_THREADS
+    
     make CC=$C_COMPILER FC=$FORTRAN_COMPILER USE_OPENMP=1 > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE OPENBLAS OK"
+    else
+      echo "OPENBLAS COULD NOT MAKE" >&2
+      return 1
+    fi
 
     make install PREFIX=$ROOTDIR/.local > /dev/null 2> /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL OPENBLAS OK"
+    else
+      echo "OPENBLAS COULD NOT MAKE INSTALL" >&2
+      return 1
+    fi
     unset MAKE_NB_JOBS
 
     cd $ROOTDIR/
diff --git a/Cocoa/installation_scripts/setup_xz b/Cocoa/installation_scripts/setup_xz
--- a/Cocoa/installation_scripts/setup_xz
+++ b/Cocoa/installation_scripts/setup_xz
@@ -31,8 +31,20 @@ if [ -z "${IGNORE_XZ_INSTALLATION}" ]; then
     CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null
 
     make -j $MAKE_NUM_THREADS all > /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE XZ OK"
+    else
+      echo "XZ COULD NOT MAKE" >&2
+    fi
 
     make install > /dev/null
+    if [ $? -eq 0 ] 
+    then
+      echo "MAKE INSTALL XZ OK"
+    else
+      echo "XZ COULD NOT MAKE INSTALL" >&2
+    fi
 
     cd ../../Cocoa
 fi
