More bash script updates

diff --git a/Cocoa/installation_scripts/setup_fortran_packages b/Cocoa/installation_scripts/setup_fortran_packages
--- a/Cocoa/installation_scripts/setup_fortran_packages
+++ b/Cocoa/installation_scripts/setup_fortran_packages
@@ -30,67 +30,59 @@ fi
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
+if [ -z "${DEBUG_FORTRAN_PACKAGES}" ]; then
+  export OUTPUT_FORTRAN_1="/dev/null"
+  export OUTPUT_FORTRAN_2="/dev/null"
+  export FORTRAN_MAKE_NUM_THREADS="${MAKE_NUM_THREADS}"
+else
+  export OUTPUT_FORTRAN_1="/dev/tty"
+  export OUTPUT_FORTRAN_2="/dev/tty"
+  export FORTRAN_MAKE_NUM_THREADS=1
+fi
 
 if [ -z "${IGNORE_FORTRAN_LAPACK_INSTALLATION}" ]; then
-  echo 'INSTALLING FORTRAN LAPACK - THIS MIGHT TAKE A WHILE'
+  echo -e '\033[1;34m''INSTALLING LAPACK FORTRAN LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/
-
   rm -rf lapack-build
   mkdir lapack-build
-
   cd ./lapack-build
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
 
-  if [ -z "${DEBUG_FORTRAN_PACKAGES}" ]; then
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
-      -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR \
-      ../${COCOA_LAPACK_DIR} > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "LAPACK CMAKE RUN DONE"
-    else
-      echo "LAPACK COULD NOT RUN CMAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "LAPACK MAKE RUN DONE"
-    else
-      echo "LAPACK COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "LAPACK MAKE INSTALL RUN DONE"
-    else
-      echo "LAPACK COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+  $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR \
+    ../${COCOA_LAPACK_DIR} > ${OUTPUT_FORTRAN_1} 2> ${OUTPUT_FORTRAN_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"LAPACK RUN CMAKE DONE"'\033[0m'
   else
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
-      -DCMAKE_C_COMPILER=$C_COMPILER --log-level=ERROR ../${COCOA_LAPACK_DIR}
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo -e '\033[0;31m'"LAPACK COULD NOT RUN CMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $FORTRAN_MAKE_NUM_THREADS all > ${OUTPUT_FORTRAN_1} 2> ${OUTPUT_FORTRAN_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"LAPACK RUN MAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"LAPACK COULD NOT RUN MAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_FORTRAN_1} 2> ${OUTPUT_FORTRAN_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"LAPACK RUN MAKE INSTALL DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"LAPACK COULD NOT RUN MAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
   
   cd $ROOTDIR
+  echo -e '\033[1;34m''\e[4mINSTALLING LAPACK FORTRAN LIBRARY''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
diff --git a/Cocoa/installation_scripts/setup_hdf5 b/Cocoa/installation_scripts/setup_hdf5
--- a/Cocoa/installation_scripts/setup_hdf5
+++ b/Cocoa/installation_scripts/setup_hdf5
@@ -42,48 +42,47 @@ if [ -z "${IGNORE_HDF5_INSTALLATION}" ]; then
     export HDF5_MAKE_NUM_THREADS=1
   fi
 
-  # --------------------------------------------------------------------------------------
-  # --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_HDF5_DIR2
-  # --------------------------------------------------------------------------------------
-  # --------------------------------------------------------------------------------------
   rm -f  CMakeCache.txt
   rm -rf CMakeFiles/
-  rm -rf cocoa_build/
-  mkdir cocoa_build
-  cd cocoa_build
+  rm -rf cocoa_HDF5_build/
+  mkdir cocoa_HDF5_build
+  cd cocoa_HDF5_build
+# --------------------------------------------------------------------------------------
+# --------------------------------------------------------------------------------------
 
-  if [ -z "${DEBUG_HDF5_PACKAGES}" ]; then
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
-      -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-      -DCMAKE_FC_COMPILER=FORTRAN_COMPILER \
-      --log-level=ERROR .. > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
-    if [ $? -eq 0 ]; then
-      echo -e '\033[0;32m'"HDF5 RUN CMAKE DONE"'\033[0m'
-    else
-      echo -e '\033[0;31m'"HDF5 COULD NOT RUN CMAKE"'\033[0m'
-      cd $ROOTDIR
-      return 1
-    fi
+  $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+    -DCMAKE_FC_COMPILER=FORTRAN_COMPILER \
+    --log-level=ERROR .. > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"HDF5 RUN CMAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"HDF5 COULD NOT RUN CMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make -j $HDF5_MAKE_NUM_THREADS > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
-    if [ $? -eq 0 ]; then
-      echo -e '\033[0;32m'"HDF5 RUN MAKE DONE"'\033[0m'
-    else
-      echo -e '\033[0;31m'"HDF5 COULD NOT RUN MAKE"'\033[0m'
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $HDF5_MAKE_NUM_THREADS > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"HDF5 RUN MAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"HDF5 COULD NOT RUN MAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make install > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
-    if [ $? -eq 0 ]; then
-      echo -e '\033[0;32m'"HDF5 RUN MAKE INSTALL DONE"'\033[0m'
-    else
-      echo -e '\033[0;31m'"HDF5 COULD NOT RUN MAKE INSTALL"'\033[0m'
-      cd $ROOTDIR
-      return 1
-    fi
+  make install > ${OUTPUT_HDF5_1} 2> ${OUTPUT_HDF5_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"HDF5 RUN MAKE INSTALL DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"HDF5 COULD NOT RUN MAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
   cd $ROOTDIR
-  echo -e '\033[1;34m''\e[4mCOMPILING HDF5 LIBRARY''\033[0m'
+  echo -e '\033[1;34m''\e[4mINSTALLING HDF5 LIBRARY''\033[0m'
 fi
diff --git a/Cocoa/installation_scripts/setup_xz b/Cocoa/installation_scripts/setup_xz
--- a/Cocoa/installation_scripts/setup_xz
+++ b/Cocoa/installation_scripts/setup_xz
@@ -32,60 +32,59 @@ fi
 if [ -z "${IGNORE_XZ_INSTALLATION}" ]; then
   echo 'INSTALLING XZ LIBRARY - THAT MIGHT TAKE A WHILE'
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd ../cocoa_installation_libraries/
-
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
+  
   #False xz file: just to trigger GIT LFS
   cp xz-5.2.5.tar.gz.xz xz-5.2.5.tar.gz
 
   tar -xf xz-5.2.5.tar.gz.xz
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd ./xz-5.2.5/
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
 
   if [ -z "${DEBUG_XZ_PACKAGE}" ]; then
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "XZ CONFIGURE RUN DONE"
-    else
-      echo "XZ COULD NOT RUN CONFIGURE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "XZ MAKE RUN DONE"
-    else
-      echo "XZ COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "XZ MAKE INSTALL RUN DONE"
-    else
-      echo "XZ COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+    export OUTPUT_XZ_1="/dev/null"
+    export OUTPUT_XZ_2="/dev/null"
+    export XZ_MAKE_NUM_THREADS="${MAKE_NUM_THREADS}"
   else
-    CC=$C_COMPILER ./configure --prefix=$ROOTDIR/.local
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
+    export OUTPUT_XZ_1="/dev/tty"
+    export OUTPUT_XZ_2="/dev/tty"
+    export XZ_MAKE_NUM_THREADS=1
+  fi
 
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi  
-        
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi 
+  CC=$C_COMPILER ./configure \
+    --prefix=$ROOTDIR/.local > ${OUTPUT_XZ_1} 2> ${OUTPUT_XZ_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"XZ RUN CONFIGURE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"XZ COULD NOT RUN CONFIGURE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make -j $XZ_MAKE_NUM_THREADS all > ${OUTPUT_XZ_1} 2> ${OUTPUT_XZ_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"XZ RUN MAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"XZ COULD NOT RUN MAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_XZ_1} 2> ${OUTPUT_XZ_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"XZ RUN MAKE INSTALL DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"XZ COULD NOT RUN MAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
