More bash script updates

diff --git a/Cocoa/installation_scripts/setup_cpp_packages b/Cocoa/installation_scripts/setup_cpp_packages
--- a/Cocoa/installation_scripts/setup_cpp_packages
+++ b/Cocoa/installation_scripts/setup_cpp_packages
@@ -30,6 +30,15 @@ fi
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
 # --------------------------------------------------------------------------------------
+if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
+  export OUTPUT_CPP_PACKAGES_1="/dev/null"
+  export OUTPUT_CPP_PACKAGES_2="/dev/null"
+  export CPP_MAKE_NUM_THREADS="${MAKE_NUM_THREADS}"
+else
+  export OUTPUT_CPP_PACKAGES_1="/dev/tty"
+  export OUTPUT_CPP_PACKAGES_2="/dev/tty"
+  export CPP_MAKE_NUM_THREADS=1
+fi
 
 # --------------------------------------------------------------------------------------
 # --------------------------------------- SPDLOG ---------------------------------------
@@ -37,56 +46,43 @@ fi
 if [ -z "${IGNORE_CPP_SPDLOG_INSTALLATION}" ]; then
   echo -e '\033[1;34m''INSTALLING SPDLOG C++ LIBRARY - \e[4mIT MAY TAKE A WHILE''\033[0m'
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_SPDLOG_DIR
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
 
   rm -f CMakeCache.txt
 
-  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
-    $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
-    -DCMAKE_CXX_COMPILER=$CXX_COMPILER --log-level=ERROR . > /dev/null 2> /dev/null
-    if [ $? -eq 0 ];then
-      echo "SPDLOG RUN CMAKE DONE"
-    else
-      echo "SPDLOG COULD NOT RUN CMAKE - CHECK SETUP_CPP_PACKAGES SCRIPT" >&2
-      cd $ROOTDIR
-      return 1
-    fi
 
-    make -j $MAKE_NUM_THREADS > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "SPDLOG RUN MAKE DONE"
-    else
-      echo "SPDLOG COULD NOT RUN MAKE" >&2
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null
-    if [ $? -eq 0 ]; then
-      echo "SPDLOG RUN MAKE INSTALL DONE"
-    else
-      echo "SPDLOG COULD NOT RUN MAKE INSTALL" >&2
-      cd $ROOTDIR
-      return 1
-    fi
+  $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+    -DCMAKE_C_COMPILER=$C_COMPILER \
+    -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
+    --log-level=ERROR . > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ];then
+    echo -e '\033[0;32m'"SPDLOG RUN CMAKE DONE"'\033[0m'
   else
-    $CMAKE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local -DCMAKE_C_COMPILER=$C_COMPILER \
-    -DCMAKE_CXX_COMPILER=$CXX_COMPILER .
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo -e '\033[0;31m'"SPDLOG COULD NOT RUN CMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make 
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    make install
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make -j $CPP_MAKE_NUM_THREADS > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"SPDLOG RUN MAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"SPDLOG COULD NOT RUN MAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"SPDLOG RUN MAKE INSTALL DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"SPDLOG COULD NOT RUN MAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
@@ -99,62 +95,51 @@ fi
 if [ -z "${IGNORE_CPP_ARMA_INSTALLATION}" ]; then
   echo -e '\033[1;34m''INSTALLING ARMADILLO C++ LIBRARY - \e[4mIT MAY TAKE A WHILE''\033[0m'
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_ARMADILLO_DIR
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
 
   rm -f CMakeCache.txt
 
-  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
+  $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
     -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
     -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
-    -DBLAS_FOUND=NO --log-level=ERROR . > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "ARMADILLO RUN CMAKE DONE"
-    else
-      echo "ARMADILLO COULD NOT RUN CMAKE"
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make clean
-    make -j $MAKE_NUM_THREADS all -Wno-dev > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "ARMADILLO RUN MAKE DONE"
-    else
-      echo "ARMADILLO COULD NOT RUN MAKE"
-      cd $ROOTDIR
-      return 1
-    fi
-
-    make install > /dev/null
-    if [ $? -eq 0 ]; then
-      echo "ARMADILLO RUN MAKE INSTALL DONE"
-    else
-      echo "ARMADILLO COULD NOT RUN MAKE INSTALL"
-      cd $ROOTDIR
-      return 1
-    fi
+    -DBLAS_FOUND=NO --log-level=ERROR . > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"ARMADILLO RUN CMAKE DONE"'\033[0m'
   else
-    $CMAKE -DBUILD_SHARED_LIBS=TRUE -DCMAKE_INSTALL_PREFIX=$ROOTDIR/.local \
-      -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER \
-      -DLAPACK_FOUND=YES -DLAPACK_LIBRARIES=$ROOTDIR/.local/lib/liblapack.so \
-      -DBLAS_FOUND=NO .
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo -e '\033[0;31m'"ARMADILLO COULD NOT RUN CMAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
 
-    make clean
-    make all
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    make install 
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+  make clean > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"ARMADILLO RUN MAKE CLEAN DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"ARMADILLO COULD NOT RUN MAKE CLEAN"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make -j $CPP_MAKE_NUM_THREADS all -Wno-dev > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"ARMADILLO RUN MAKE DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"ARMADILLO COULD NOT RUN MAKE"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  make install > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"ARMADILLO RUN MAKE INSTALL DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"ARMADILLO COULD NOT RUN MAKE INSTALL"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
 
   cd $ROOTDIR
@@ -167,7 +152,11 @@ fi
 if [ -z "${IGNORE_CPP_CARMA_INSTALLATION}" ]; then
   echo -e '\033[1;34m''INSTALLING CARMA C++ LIBRARY''\033[0m'
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_CARMA_DIR
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
 
   rm -rf $ROOTDIR/.local/include/carma/
   
@@ -187,42 +176,35 @@ fi
 if [ -z "${IGNORE_CPP_BOOST_INSTALLATION}" ]; then
   echo -e '\033[1;34m''INSTALLING BOOST C++ LIBRARY - \e[4mIT WILL TAKE A WHILE''\033[0m'
 
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
   cd $ROOTDIR/../cocoa_installation_libraries/$COCOA_BOOST_DIR
+  # --------------------------------------------------------------------------------------
+  # --------------------------------------------------------------------------------------
 
-  if [ -z "${DEBUG_CPP_PACKAGES}" ]; then
-    ./bootstrap.sh --prefix=$ROOTDIR/.local > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "BOOST RUN BOOTSTRAP DONE"
-    else
-      echo "BOOST COULD NOT RUN BOOTSTRAP" >&2
-      return 1
-    fi
-
-    ./b2 --with=regex install --without-python --without-thread \
-    --without-timer --without-mpi --without-atomic > /dev/null 2> /dev/null
-    if [ $? -eq 0 ]; then
-      echo "BOOST RUN B2 DONE"
-    else
-      echo "BOOST COULD NOT RUN B2"
-      return 1
-    fi
+  ./bootstrap.sh \
+    --prefix=$ROOTDIR/.local > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"BOOST RUN BOOTSTRAP DONE"'\033[0m'
   else
-    ./bootstrap.sh --prefix=$ROOTDIR/.local 
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
-    
-    ./b2 --with=regex install --without-python --without-thread \
-    --without-timer --without-mpi --without-atomic
-    if [ $? -ne 0 ];then
-      cd $ROOTDIR
-      return 1
-    fi
+    echo -e '\033[0;31m'"BOOST COULD NOT RUN BOOTSTRAP"'\033[0m'
+    cd $ROOTDIR
+    return 1
+  fi
+
+  ./b2 --with=regex install --without-python --without-thread \
+    --without-timer --without-mpi \
+    --without-atomic > ${OUTPUT_CPP_PACKAGES_1} 2> ${OUTPUT_CPP_PACKAGES_2}
+  if [ $? -eq 0 ]; then
+    echo -e '\033[0;32m'"BOOST RUN B2 DONE"'\033[0m'
+  else
+    echo -e '\033[0;31m'"BOOST COULD NOT RUN B2"'\033[0m'
+    cd $ROOTDIR
+    return 1
   fi
   
   cd $ROOTDIR
-  echo -e '\033[1;34m''\e[4mINSTALLING BOSST C++ LIBRARY DONE''\033[0m'
+  echo -e '\033[1;34m''\e[4mINSTALLING BOOST C++ LIBRARY DONE''\033[0m'
 fi
 
 # --------------------------------------------------------------------------------------
