update

diff --git a/Cocoa/installation_scripts/setup_c_packages b/Cocoa/installation_scripts/setup_c_packages
--- a/Cocoa/installation_scripts/setup_c_packages
+++ b/Cocoa/installation_scripts/setup_c_packages
@@ -1,26 +1,26 @@
 if [ -z "${ROOTDIR}" ]; then
     echo 'ERROR ROOTDIR not defined'
-    return
+    return 1
 fi
 if [ -z "${CXX_COMPILER}" ]; then
     echo 'ERROR CXX_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${C_COMPILER}" ]; then
     echo 'ERROR C_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${FORTRAN_COMPILER}" ]; then
     echo 'ERROR C_COMPILER not defined'
-    return
+    return 1
 fi
 if [ -z "${CMAKE}" ]; then
     echo 'ERROR CMAKE not defined'
-    return
+    return 1
 fi
 if [ -z "${MAKE_NUM_THREADS}" ]; then
     echo 'ERROR MAKE_NUM_THREADS not defined'
-    return
+    return 1
 fi
 # ----------------------------------------------------------------------------
 # ----------------------------------------------------------------------------
@@ -94,9 +94,9 @@ if [ -z "${IGNORE_C_GSL_INSTALLATION}" ]; then
     make -j $MAKE_NUM_THREADS all > /dev/null 2> /dev/null
     if [ $? -eq 0 ] 
     then
-      echo "MAKE CFITSIO OK"
+      echo "MAKE GSL OK"
     else
-      echo "CFITSIO COULD NOT MAKE" >&2
+      echo "GSL COULD NOT MAKE" >&2
       return 1
     fi
 
diff --git a/Cocoa/setup_cocoa_installation_packages b/Cocoa/setup_cocoa_installation_packages
--- a/Cocoa/setup_cocoa_installation_packages
+++ b/Cocoa/setup_cocoa_installation_packages
@@ -75,20 +75,60 @@ addvar PATH $ROOTDIR/.local/bin
 # ----------------------------------------------------------------------------
 
 source ./installation_scripts/setup_xz
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_xz SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_decompress_files
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_decompress_files SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_cmake
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_cmake SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_openblas
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_openblas SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_pip_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_pip_packages SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_cpp_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_cpp_packages SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_c_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_c_packages SCRIPT" >&2
+return 1
+fi
 
 source ./installation_scripts/setup_fortran_packages
+if [ $? -ne 0 ] 
+then
+echo "FAILED setup_fortran_packages SCRIPT" >&2
+return 1
+fi
 
 
 # ----------------------------------------------------------------------------
